import {
  Department,
  User,
  RegistrationRound,
  ResearchProject,
  Council,
  AuditLog,
} from '@/lib/types';

// ==========================================
// 1. DANH MỤC KHOA / PHÒNG (6 KHOA/PHÒNG)
// ==========================================
export const SEED_DEPARTMENTS: Department[] = [
  { id: 'dept-01', code: 'TM', name: 'Khoa Tim mạch Can thiệp', type: 'CLINICAL' },
  { id: 'dept-02', code: 'HSTC', name: 'Khoa Hồi sức tích cực - Chống độc', type: 'CLINICAL' },
  { id: 'dept-03', code: 'UB', name: 'Khoa Ung bướu & Xạ trị', type: 'CLINICAL' },
  { id: 'dept-04', code: 'XN', name: 'Khoa Hóa sinh - Huyết học - Vi sinh', type: 'SUB_CLINICAL' },
  { id: 'dept-05', code: 'DL', name: 'Khoa Dược lâm sàng', type: 'SUB_CLINICAL' },
  { id: 'dept-06', code: 'NCKH', name: 'Phòng Quản lý NCKH & Đào tạo', type: 'ADMINISTRATIVE' },
  { id: 'dept-07', code: 'TCKT', name: 'Phòng Tài chính - Kế toán', type: 'ADMINISTRATIVE' },
  { id: 'dept-08', code: 'BGD', name: 'Ban Giám đốc Bệnh viện', type: 'ADMINISTRATIVE' },
];

// ==========================================
// 2. TÀI KHOẢN NGƯỜI DÙNG DEMO (15 USERS, 8 VAI TRÒ)
// ==========================================
export const SEED_USERS: User[] = [
  {
    id: 'user-01',
    email: 'researcher1@hospital.gov.vn',
    fullName: 'BS.CKII. Nguyễn Văn An',
    role: 'RESEARCHER',
    departmentId: 'dept-01',
    phone: '0912345671',
    academicTitle: 'BS.CKII',
    degree: 'Bác sĩ chuyên khoa II Tim mạch',
  },
  {
    id: 'user-02',
    email: 'researcher2@hospital.gov.vn',
    fullName: 'ThS.BS. Trần Thị Mai',
    role: 'RESEARCHER',
    departmentId: 'dept-02',
    phone: '0912345672',
    academicTitle: 'ThS.BS',
    degree: 'Thạc sĩ Hồi sức cấp cứu',
  },
  {
    id: 'user-03',
    email: 'researcher3@hospital.gov.vn',
    fullName: 'TS.BS. Lê Văn Cường',
    role: 'RESEARCHER',
    departmentId: 'dept-03',
    phone: '0912345673',
    academicTitle: 'TS.BS',
    degree: 'Tiến sĩ Ung bướu',
  },
  {
    id: 'user-04',
    email: 'research_office@hospital.gov.vn',
    fullName: 'ThS. Lê Hoàng Long',
    role: 'RESEARCH_OFFICE',
    departmentId: 'dept-06',
    phone: '0912345674',
    academicTitle: 'ThS',
    degree: 'Chuyên viên Quản lý NCKH',
  },
  {
    id: 'user-05',
    email: 'council_chair@hospital.gov.vn',
    fullName: 'PGS.TS.BS. Phạm Đức Dũng',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-01',
    phone: '0912345675',
    academicTitle: 'PGS.TS.BS',
    degree: 'Phó Giáo sư Tim mạch',
  },
  {
    id: 'user-06',
    email: 'council_member@hospital.gov.vn',
    fullName: 'TS.BS. Hoàng Minh Tuấn',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-02',
    phone: '0912345676',
    academicTitle: 'TS.BS',
    degree: 'Tiến sĩ Y khoa',
  },
  {
    id: 'user-07',
    email: 'council_sec@hospital.gov.vn',
    fullName: 'BS.CKI. Đỗ Bích Ngọc',
    role: 'COUNCIL_SECRETARY',
    departmentId: 'dept-06',
    phone: '0912345677',
    academicTitle: 'BS.CKI',
    degree: 'Thư ký Hội đồng Khoa học',
  },
  {
    id: 'user-08',
    email: 'ethics_office@hospital.gov.vn',
    fullName: 'TS.BS. Vũ Thị Hồng Hạnh',
    role: 'ETHICS_OFFICE',
    departmentId: 'dept-06',
    phone: '0912345678',
    academicTitle: 'TS.BS',
    degree: 'Thường trực Hội đồng Đạo đức Y sinh',
  },
  {
    id: 'user-09',
    email: 'finance_officer@hospital.gov.vn',
    fullName: 'CN. Nguyễn Thị Thu Hà',
    role: 'FINANCE_OFFICER',
    departmentId: 'dept-07',
    phone: '0912345679',
    academicTitle: 'Cử nhân',
    degree: 'Phụ trách Kế toán NCKH',
  },
  {
    id: 'user-10',
    email: 'director@hospital.gov.vn',
    fullName: 'GS.TS.BS. Vũ Đình Khoa',
    role: 'DIRECTOR',
    departmentId: 'dept-08',
    phone: '0912345680',
    academicTitle: 'GS.TS.BS',
    degree: 'Giám đốc Bệnh viện',
  },
  {
    id: 'user-11',
    email: 'admin@hospital.gov.vn',
    fullName: 'KS. Trịnh Quốc Bảo',
    role: 'ADMIN',
    departmentId: 'dept-06',
    phone: '0912345681',
    academicTitle: 'Kỹ sư CNTT',
    degree: 'Quản trị viên Hệ thống CRMS',
  },
  {
    id: 'user-12',
    email: 'pharmacist@hospital.gov.vn',
    fullName: 'DSCKII. Bùi Thanh Tùng',
    role: 'RESEARCHER',
    departmentId: 'dept-05',
    phone: '0912345682',
    academicTitle: 'DSCKII',
    degree: 'Dược sĩ chuyên khoa II',
  },
  {
    id: 'user-13',
    email: 'lab_head@hospital.gov.vn',
    fullName: 'TS.BS. Phan Quỳnh Nga',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-04',
    phone: '0912345683',
    academicTitle: 'TS.BS',
    degree: 'Trưởng khoa Xét nghiệm',
  },
  {
    id: 'user-14',
    email: 'nurse_head@hospital.gov.vn',
    fullName: 'ThS. Đặng Thị Kim Oanh',
    role: 'RESEARCHER',
    departmentId: 'dept-02',
    phone: '0912345684',
    academicTitle: 'ThS. Điều dưỡng',
    degree: 'Thạc sĩ Điều dưỡng Hồi sức',
  },
  {
    id: 'user-15',
    email: 'reviewer2@hospital.gov.vn',
    fullName: 'PGS.TS.BS. Ngô Gia Tiến',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-03',
    phone: '0912345685',
    academicTitle: 'PGS.TS.BS',
    degree: 'Chuyên gia Phản biện Ngoại khoa',
  },
];

// ==========================================
// 3. ĐỢT ĐĂNG KÝ (3 ĐỢT)
// ==========================================
export const SEED_REGISTRATION_ROUNDS: RegistrationRound[] = [
  {
    id: 'round-2026-01',
    code: 'DOT-2026-01',
    name: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2026',
    year: 2026,
    startDate: '2026-01-05',
    endDate: '2026-03-31',
    targetAudience: 'Toàn thể Bác sĩ, Dược sĩ, Điều dưỡng và Kỹ thuật viên bệnh viện',
    status: 'OPEN',
    description: 'Ưu tiên các đề tài cải tiến quy trình lâm sàng, ứng dụng kỹ thuật mới và an toàn người bệnh.',
    maxBudget: 150000000,
    totalSubmissions: 8,
  },
  {
    id: 'round-2025-02',
    code: 'DOT-2025-02',
    name: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 2 Năm 2025',
    year: 2025,
    startDate: '2025-07-01',
    endDate: '2025-09-30',
    targetAudience: 'Cán bộ y tế các khoa Lâm sàng và Cận lâm sàng',
    status: 'CLOSED',
    description: 'Tập trung nghiên cứu dịch tễ học bệnh viện và quản lý kháng kháng sinh.',
    maxBudget: 100000000,
    totalSubmissions: 12,
  },
  {
    id: 'round-2025-01',
    code: 'DOT-2025-01',
    name: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    year: 2025,
    startDate: '2025-01-10',
    endDate: '2025-03-31',
    targetAudience: 'Toàn thể cán bộ nhân viên bệnh viện',
    status: 'CLOSED',
    description: 'Nghiên cứu khoa học thường niên phục vụ nâng cao chất lượng khám chữa bệnh.',
    maxBudget: 80000000,
    totalSubmissions: 15,
  },
];

// ==========================================
// 4. DANH SÁCH 20 ĐỀ TÀI PHÂN BỔ TRẠNG THÁI
// ==========================================
export const SEED_PROJECTS: ResearchProject[] = [
  // 1. Đề tài Đang thực hiện (IN_PROGRESS) - Có đạo đức đạt
  {
    id: 'proj-01',
    projectCode: 'DT-2025-001',
    proposalCode: 'DX-2025-001',
    title: 'Đánh giá hiệu quả can thiệp động mạch vành qua da ở bệnh nhân nhồi máu cơ tim cấp cao tuổi',
    summary: 'Nghiên cứu tiến cứu theo dõi 120 bệnh nhân trên 75 tuổi can thiệp stent phủ thuốc thế hệ mới.',
    researchField: 'Tim mạch',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-01',
    principalInvestigatorName: 'BS.CKII. Nguyễn Văn An',
    departmentId: 'dept-01',
    departmentName: 'Khoa Tim mạch Can thiệp',
    startDate: '01/04/2025',
    endDate: '31/03/2026',
    estimatedBudget: 95000000,
    approvedBudget: 85000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 65,
    status: 'IN_PROGRESS',
    proposalStatus: 'VALID',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    createdAt: '15/01/2025',
    submittedAt: '20/01/2025',
    approvedAt: '25/03/2025',
    members: [
      {
        id: 'mem-01',
        projectId: 'proj-01',
        fullName: 'BS.CKII. Nguyễn Văn An',
        academicRank: 'BS.CKII',
        unit: 'Khoa Tim mạch Can thiệp',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 50,
      },
      {
        id: 'mem-02',
        projectId: 'proj-01',
        fullName: 'ThS.BS. Trần Thị Mai',
        academicRank: 'ThS.BS',
        unit: 'Khoa Hồi sức tích cực',
        roleInProject: 'THÀNH_VIÊN_CHÍNH',
        contributionPercentage: 30,
      },
    ],
    documents: [
      {
        id: 'doc-01',
        projectId: 'proj-01',
        documentType: 'DETAILED_OUTLINE',
        title: 'Đề cương chi tiết đề tài',
        currentVersion: 2,
        currentVersionId: 'ver-02',
        versions: [
          {
            id: 'ver-01',
            documentId: 'doc-01',
            version: 1,
            fileName: 'De_cuong_v1.pdf',
            fileSize: '2.4 MB',
            uploadedBy: 'user-01',
            uploadedByName: 'BS.CKII. Nguyễn Văn An',
            uploadedAt: '20/01/2025',
            downloadUrl: '#',
            isCurrent: false,
          },
          {
            id: 'ver-02',
            documentId: 'doc-01',
            version: 2,
            fileName: 'De_cuong_hoan_thien_v2.pdf',
            fileSize: '2.6 MB',
            uploadedBy: 'user-01',
            uploadedByName: 'BS.CKII. Nguyễn Văn An',
            uploadedAt: '15/03/2025',
            downloadUrl: '#',
            notes: 'Đã chỉnh sửa theo góp ý Hội đồng',
            isCurrent: true,
          },
        ],
      },
    ],
    milestones: [
      {
        id: 'ms-01',
        projectId: 'proj-01',
        title: 'Thu thập mẫu nghiên cứu giai đoạn 1',
        description: 'Thu thập đủ 60 bệnh nhân đầu tiên',
        targetDate: '30/08/2025',
        actualDate: '25/08/2025',
        weightPercentage: 40,
        status: 'COMPLETED',
        deliverables: 'Báo cáo số liệu 60 bệnh nhân',
      },
      {
        id: 'ms-02',
        projectId: 'proj-01',
        title: 'Thu thập mẫu giai đoạn 2 và phân tích số liệu',
        description: 'Hoàn thành 120 ca và chạy mô hình SPSS',
        targetDate: '30/12/2025',
        weightPercentage: 40,
        status: 'IN_PROGRESS',
        deliverables: 'Bộ dữ liệu SPSS và biểu bảng phân tích',
      },
    ],
    progressReports: [
      {
        id: 'pr-01',
        projectId: 'proj-01',
        period: 'Báo cáo định kỳ 6 tháng (Kỳ 1)',
        reportingDate: '15/09/2025',
        workCompleted: 'Đã thu thập 65 bệnh nhân, hoàn thành sàng lọc lâm sàng.',
        resultsAchieved: 'Tỷ lệ thành công thủ thuật đạt 96.8%, không có biến cố tử vong nội viện.',
        completedPercentage: 55,
        nextPlan: 'Tiếp tục thu thập 55 ca tiếp theo và theo dõi tái khám 3 tháng.',
        evidenceUrls: [{ name: 'Danh_sach_benh_nhan_ma_hoa.xlsx', url: '#' }],
        status: 'APPROVED',
        reviewComment: 'Tiến độ tốt, đúng kế hoạch.',
        reviewedBy: 'ThS. Lê Hoàng Long',
        reviewedAt: '20/09/2025',
      },
    ],
    changeRequests: [],
    ethicsReview: {
      id: 'eth-01',
      projectId: 'proj-01',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: false,
        involvesNewInterventionsOrDrugs: true,
      },
      ethicsRequired: true,
      dossierSubmittedDate: '01/02/2025',
      status: 'ETHICS_APPROVED',
      decisionNumber: 'CN-DD-2025/12',
      approvalDate: '15/02/2025',
      expiryDate: '15/02/2026',
      certificateDocUrl: '#',
    },
    financialSummary: {
      id: 'fin-01',
      projectId: 'proj-01',
      fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
      estimatedBudget: 95000000,
      approvedBudget: 85000000,
      allocatedBudget: 50000000,
      disbursedBudget: 42000000,
      settledBudget: 0,
      refundableBudget: 0,
      status: 'NOT_SETTLED',
    },
    decisions: [
      {
        id: 'dec-01',
        projectId: 'proj-01',
        decisionNumber: 'QĐ-NCKH/2025/45',
        decisionDate: '25/03/2025',
        type: 'ASSIGNMENT',
        effectiveDate: '01/04/2025',
        durationMonths: 12,
        approvedBudget: 85000000,
        signatoryName: 'GS.TS.BS. Vũ Đình Khoa',
        signatoryRole: 'Giám đốc Bệnh viện',
        status: 'APPROVED',
        approvedAt: '25/03/2025',
      },
    ],
    statusHistory: [
      {
        id: 'sh-01',
        projectId: 'proj-01',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        changedBy: 'user-01',
        changedByName: 'BS.CKII. Nguyễn Văn An',
        userRole: 'RESEARCHER',
        changedAt: '20/01/2025 09:30',
        action: 'Nộp hồ sơ đề xuất',
      },
      {
        id: 'sh-02',
        projectId: 'proj-01',
        fromStatus: 'SUBMITTED',
        toStatus: 'VALID',
        changedBy: 'user-04',
        changedByName: 'ThS. Lê Hoàng Long',
        userRole: 'RESEARCH_OFFICE',
        changedAt: '25/01/2025 14:15',
        action: 'Xác nhận hồ sơ hợp lệ',
      },
      {
        id: 'sh-03',
        projectId: 'proj-01',
        fromStatus: 'PROPOSAL_APPROVED',
        toStatus: 'IN_PROGRESS',
        changedBy: 'user-10',
        changedByName: 'GS.TS.BS. Vũ Đình Khoa',
        userRole: 'DIRECTOR',
        changedAt: '25/03/2025 16:00',
        action: 'Ký Quyết định giao thực hiện đề tài',
      },
    ],
  },

  // 2. Đề tài Mới nộp đề xuất (SUBMITTED) - Chờ Phòng NCKH kiểm tra
  {
    id: 'proj-02',
    proposalCode: 'DX-2026-002',
    title: 'Khảo sát tỷ lệ nhiễm khuẩn vết mổ và các yếu tố liên quan tại Khoa Ngoại tổng hợp',
    summary: 'Nghiên cứu cắt ngang trên 300 bệnh nhân sau phẫu thuật ổ bụng trong 6 tháng đầu năm 2026.',
    researchField: 'Dịch tễ học',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'DỊCH_TỄ_HỌC',
    principalInvestigatorId: 'user-02',
    principalInvestigatorName: 'ThS.BS. Trần Thị Mai',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '01/05/2026',
    endDate: '31/10/2026',
    estimatedBudget: 45000000,
    approvedBudget: 0,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 0,
    status: 'DRAFT',
    proposalStatus: 'SUBMITTED',
    ethicsRequired: true,
    ethicsStatus: 'DOSSIER_SUBMITTED',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2026',
    createdAt: '10/01/2026',
    submittedAt: '12/01/2026',
    members: [
      {
        id: 'mem-03',
        projectId: 'proj-02',
        fullName: 'ThS.BS. Trần Thị Mai',
        academicRank: 'ThS.BS',
        unit: 'Khoa Hồi sức tích cực',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 60,
      },
    ],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [
      {
        id: 'sh-04',
        projectId: 'proj-02',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        changedBy: 'user-02',
        changedByName: 'ThS.BS. Trần Thị Mai',
        userRole: 'RESEARCHER',
        changedAt: '12/01/2026 10:00',
        action: 'Nộp hồ sơ đề xuất trực tuyến',
      },
    ],
  },

  // 3. Đề tài Bị yêu cầu bổ sung hồ sơ (REVISION_REQUIRED)
  {
    id: 'proj-03',
    proposalCode: 'DX-2026-003',
    title: 'Nghiên cứu nồng độ Vancomycin đáy trong máu và mối liên quan đến độc tính trên thận ở bệnh nhân ICU',
    summary: 'Định lượng TDM Vancomycin nhằm tối ưu hóa liều điều trị và phòng ngừa suy thận cấp.',
    researchField: 'Dược lâm sàng',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-12',
    principalInvestigatorName: 'DSCKII. Bùi Thanh Tùng',
    departmentId: 'dept-05',
    departmentName: 'Khoa Dược lâm sàng',
    startDate: '01/06/2026',
    endDate: '31/12/2026',
    estimatedBudget: 60000000,
    approvedBudget: 0,
    fundingSource: 'TỰ_TÚC',
    progressPercentage: 0,
    status: 'DRAFT',
    proposalStatus: 'REVISION_REQUIRED',
    ethicsRequired: true,
    ethicsStatus: 'DOSSIER_SUBMITTED',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2026',
    createdAt: '15/01/2026',
    submittedAt: '18/01/2026',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [
      {
        id: 'sh-05',
        projectId: 'proj-03',
        fromStatus: 'UNDER_ADMIN_REVIEW',
        toStatus: 'REVISION_REQUIRED',
        changedBy: 'user-04',
        changedByName: 'ThS. Lê Hoàng Long',
        userRole: 'RESEARCH_OFFICE',
        changedAt: '22/01/2026 15:30',
        action: 'Yêu cầu bổ sung dự toán kinh phí chi tiết theo mẫu số 03/NCKH',
        comment: 'Cần làm rõ chi phí test định lượng miễn dịch huỳnh quang.',
      },
    ],
  },

  // 4. Đề tài Đang họp Hội đồng xét duyệt đề cương (UNDER_COUNCIL_REVIEW)
  {
    id: 'proj-04',
    proposalCode: 'DX-2026-004',
    title: 'Ứng dụng thang điểm NEWS2 trong cảnh báo sớm suy hô hấp ở bệnh nhân thở máy không xâm lấn',
    summary: 'Đánh giá độ nhạy và độ đặc hiệu của NEWS2 trong dự đoán thất bại NIV.',
    researchField: 'Hồi sức cấp cứu',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'CẢI_TIẾN_KỸ_THUẬT',
    principalInvestigatorId: 'user-14',
    principalInvestigatorName: 'ThS. Đặng Thị Kim Oanh',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '01/04/2026',
    endDate: '31/10/2026',
    estimatedBudget: 35000000,
    approvedBudget: 0,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 0,
    status: 'DRAFT',
    proposalStatus: 'VALID',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2026',
    createdAt: '08/01/2026',
    submittedAt: '10/01/2026',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },

  // 5. Đề tài Đã duyệt đề cương, Chờ Quyết định giao (PROPOSAL_APPROVED)
  {
    id: 'proj-05',
    projectCode: 'DT-2026-005',
    proposalCode: 'DX-2026-005',
    title: 'Khảo sát đột biến gen EGFR trên bệnh nhân ung thư phổi không tế bào nhỏ giai đoạn muộn',
    summary: 'Xác định tỷ lệ các exon 19, 21 bằng kỹ thuật Real-time PCR.',
    researchField: 'Ung bướu',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-03',
    principalInvestigatorName: 'TS.BS. Lê Văn Cường',
    departmentId: 'dept-03',
    departmentName: 'Khoa Ung bướu & Xạ trị',
    startDate: '01/03/2026',
    endDate: '28/02/2027',
    estimatedBudget: 120000000,
    approvedBudget: 110000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 0,
    status: 'PROPOSAL_APPROVED',
    proposalStatus: 'VALID',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2026',
    createdAt: '06/01/2026',
    submittedAt: '12/01/2026',
    approvedAt: '02/02/2026',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [
      {
        id: 'dec-05',
        projectId: 'proj-05',
        decisionNumber: 'Dự thảo QĐ-NCKH/2026/08',
        decisionDate: '05/02/2026',
        type: 'ASSIGNMENT',
        effectiveDate: '01/03/2026',
        approvedBudget: 110000000,
        signatoryName: 'GS.TS.BS. Vũ Đình Khoa',
        signatoryRole: 'Giám đốc Bệnh viện',
        status: 'SUBMITTED_FOR_APPROVAL',
      },
    ],
    statusHistory: [],
  },

  // 6. Đề tài Đang thực hiện nhưng Xin gia hạn (EXTENSION_REQUESTED)
  {
    id: 'proj-06',
    projectCode: 'DT-2025-006',
    proposalCode: 'DX-2025-006',
    title: 'Khảo sát tỷ lệ đề kháng kháng sinh của vi khuẩn Gram âm phân lập tại các khoa Hồi sức',
    summary: 'Thu thập 450 chủng Acinetobacter baumannii, Pseudomonas aeruginosa và Klebsiella pneumoniae.',
    researchField: 'Vi sinh',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'DỊCH_TỄ_HỌC',
    principalInvestigatorId: 'user-13',
    principalInvestigatorName: 'TS.BS. Phan Quỳnh Nga',
    departmentId: 'dept-04',
    departmentName: 'Khoa Hóa sinh - Huyết học - Vi sinh',
    startDate: '01/03/2025',
    endDate: '28/02/2026',
    estimatedBudget: 70000000,
    approvedBudget: 65000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 80,
    status: 'IN_PROGRESS',
    proposalStatus: 'VALID',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    createdAt: '10/01/2025',
    submittedAt: '15/01/2025',
    approvedAt: '20/02/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [
      {
        id: 'cr-01',
        projectId: 'proj-06',
        type: 'EXTENSION',
        title: 'Xin gia hạn thực hiện đề tài thêm 03 tháng',
        currentInfo: 'Ngày kết thúc hiện tại: 28/02/2026',
        proposedInfo: 'Ngày kết thúc đề nghị: 31/05/2026',
        reason: 'Do thời gian mua sắm hóa chất định danh tự động Vitek 2 bị chậm 2 tháng.',
        status: 'SUBMITTED',
        submittedAt: '10/01/2026',
        submittedBy: 'user-13',
        submittedByName: 'TS.BS. Phan Quỳnh Nga',
      },
    ],
    decisions: [],
    statusHistory: [],
  },

  // 7. Đề tài Đang chờ thẩm định hồ sơ nghiệm thu (WAITING_ACCEPTANCE)
  {
    id: 'proj-07',
    projectCode: 'DT-2025-007',
    proposalCode: 'DX-2025-007',
    title: 'Đánh giá mức độ hài lòng của người bệnh nội trú tại các khoa lâm sàng năm 2025',
    summary: 'Khảo sát 600 bệnh nhân theo bộ công cụ chuẩn 5 nhóm tiêu chí của Bộ Y tế.',
    researchField: 'Quản lý y tế',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'QUẢN_LÝ_Y_TẾ',
    principalInvestigatorId: 'user-04',
    principalInvestigatorName: 'ThS. Lê Hoàng Long',
    departmentId: 'dept-06',
    departmentName: 'Phòng Quản lý NCKH & Đào tạo',
    startDate: '01/01/2025',
    endDate: '31/12/2025',
    estimatedBudget: 40000000,
    approvedBudget: 35000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 100,
    status: 'IN_PROGRESS',
    proposalStatus: 'VALID',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    createdAt: '05/01/2025',
    submittedAt: '10/01/2025',
    approvedAt: '25/01/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    acceptanceDossier: {
      id: 'acc-01',
      projectId: 'proj-07',
      submissionDate: '15/01/2026',
      productsSummary: '01 Báo cáo tổng kết 75 trang, 01 Bộ khuyến nghị cải tiến chất lượng phục vụ.',
      evidenceUrls: [{ name: 'Bao_cao_tong_ket_hai_long_2025.pdf', url: '#' }],
      status: 'SUBMITTED',
    },
    decisions: [],
    statusHistory: [],
  },

  // 8. Đề tài Đã Nghiệm thu Đạt (ACCEPTED) - Chờ QĐ công nhận
  {
    id: 'proj-08',
    projectCode: 'DT-2024-008',
    proposalCode: 'DX-2024-008',
    title: 'Nghiên cứu xây dựng phác đồ dự phòng thuyên tắc huyết khối tĩnh mạch ở bệnh nhân phẫu thuật chỉnh hình',
    summary: 'Nghiên cứu can thiệp không đối chứng trên 150 bệnh nhân thay khớp háng và khớp gối.',
    researchField: 'Ngoại khoa',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-01',
    principalInvestigatorName: 'BS.CKII. Nguyễn Văn An',
    departmentId: 'dept-01',
    departmentName: 'Khoa Tim mạch Can thiệp',
    startDate: '01/06/2024',
    endDate: '31/05/2025',
    estimatedBudget: 80000000,
    approvedBudget: 75000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 100,
    status: 'ACCEPTED',
    proposalStatus: 'VALID',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    createdAt: '10/05/2024',
    submittedAt: '20/05/2024',
    approvedAt: '01/06/2024',
    completedAt: '15/07/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    financialSummary: {
      id: 'fin-08',
      projectId: 'proj-08',
      fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
      estimatedBudget: 80000000,
      approvedBudget: 75000000,
      allocatedBudget: 75000000,
      disbursedBudget: 74200000,
      settledBudget: 74200000,
      refundableBudget: 800000,
      status: 'SETTLED',
    },
    decisions: [
      {
        id: 'dec-08',
        projectId: 'proj-08',
        decisionNumber: 'QĐ-CN/2025/88',
        decisionDate: '20/07/2025',
        type: 'RECOGNITION',
        effectiveDate: '20/07/2025',
        signatoryName: 'GS.TS.BS. Vũ Đình Khoa',
        signatoryRole: 'Giám đốc Bệnh viện',
        status: 'APPROVED',
      },
    ],
    statusHistory: [],
  },

  // 9. Đề tài Đã Đóng & Lưu trữ số (ARCHIVED)
  {
    id: 'proj-09',
    projectCode: 'DT-2024-009',
    proposalCode: 'DX-2024-009',
    title: 'Khảo sát mô hình bệnh tật và tử vong tại Khoa Hồi sức tích cực giai đoạn 2021 - 2023',
    summary: 'Phân tích hồi cứu 1.800 hồ sơ bệnh án điều trị tại ICU.',
    researchField: 'Dịch tễ học',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'DỊCH_TỄ_HỌC',
    principalInvestigatorId: 'user-02',
    principalInvestigatorName: 'ThS.BS. Trần Thị Mai',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '01/01/2024',
    endDate: '31/12/2024',
    estimatedBudget: 50000000,
    approvedBudget: 45000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 100,
    status: 'ARCHIVED',
    proposalStatus: 'VALID',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    createdAt: '01/12/2023',
    submittedAt: '15/12/2023',
    approvedAt: '28/12/2023',
    completedAt: '15/01/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    financialSummary: {
      id: 'fin-09',
      projectId: 'proj-09',
      fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
      estimatedBudget: 50000000,
      approvedBudget: 45000000,
      allocatedBudget: 45000000,
      disbursedBudget: 45000000,
      settledBudget: 45000000,
      refundableBudget: 0,
      status: 'FINANCIAL_COMPLETED',
    },
    decisions: [],
    statusHistory: [],
  },

  // 10. Đề tài Bị từ chối / Không thông qua (REJECTED)
  {
    id: 'proj-10',
    proposalCode: 'DX-2025-010',
    title: 'Thử nghiệm lâm sàng sử dụng bài thuốc đông y gia truyền hỗ trợ điều trị đái tháo đường type 2',
    summary: 'Chưa có đủ dữ liệu tiền lâm sàng và tiêu chuẩn hóa thành phần dược liệu.',
    researchField: 'Dược lâm sàng',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-12',
    principalInvestigatorName: 'DSCKII. Bùi Thanh Tùng',
    departmentId: 'dept-05',
    departmentName: 'Khoa Dược lâm sàng',
    startDate: '01/06/2025',
    endDate: '31/12/2025',
    estimatedBudget: 150000000,
    approvedBudget: 0,
    fundingSource: 'TỰ_TÚC',
    progressPercentage: 0,
    status: 'REJECTED',
    proposalStatus: 'REJECTED',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_REJECTED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    createdAt: '15/01/2025',
    submittedAt: '20/01/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [
      {
        id: 'sh-10',
        projectId: 'proj-10',
        fromStatus: 'UNDER_COUNCIL_REVIEW',
        toStatus: 'REJECTED',
        changedBy: 'user-05',
        changedByName: 'PGS.TS.BS. Phạm Đức Dũng',
        userRole: 'COUNCIL_MEMBER',
        changedAt: '28/02/2025',
        action: 'Hội đồng Khoa học kết luận không thông qua đề cương',
        comment: 'Chưa có bằng chứng độc tính cấp và bán trường diễn trên động vật thực nghiệm.',
      },
    ],
  },
  // Các đề tài khác mô phỏng (11 -> 20)
  {
    id: 'proj-11',
    projectCode: 'DT-2025-011',
    proposalCode: 'DX-2025-011',
    title: 'Đánh giá tuân thủ quy trình kiểm soát nhiễm khuẩn của nhân viên y tế tại Khoa Cấp cứu',
    summary: 'Quan sát trực tiếp 1.000 cơ hội rửa tay và mang phương tiện phòng hộ cá nhân.',
    researchField: 'Quản lý y tế',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'QUẢN_LÝ_Y_TẾ',
    principalInvestigatorId: 'user-14',
    principalInvestigatorName: 'ThS. Đặng Thị Kim Oanh',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '01/03/2025',
    endDate: '30/11/2025',
    estimatedBudget: 25000000,
    approvedBudget: 20000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 100,
    status: 'ACCEPTED',
    proposalStatus: 'VALID',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '10/01/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-12',
    projectCode: 'DT-2025-012',
    proposalCode: 'DX-2025-012',
    title: 'Ứng dụng kỹ thuật nhuộm hóa mô miễn dịch HER2 trong chẩn đoán ung thư biểu mô tuyến vú',
    summary: 'Đánh giá sự phù hợp giữa kỹ thuật IHC và giải trình tự gen.',
    researchField: 'Ung bướu',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-03',
    principalInvestigatorName: 'TS.BS. Lê Văn Cường',
    departmentId: 'dept-03',
    departmentName: 'Khoa Ung bướu & Xạ trị',
    startDate: '01/04/2025',
    endDate: '31/03/2026',
    estimatedBudget: 85000000,
    approvedBudget: 80000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 70,
    status: 'IN_PROGRESS',
    proposalStatus: 'VALID',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '15/01/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-13',
    proposalCode: 'DX-2026-013',
    title: 'Khảo sát kiến thức và thực hành sơ cấp cứu ngưng tim ngưng thở của điều dưỡng mới tuyển dụng',
    summary: 'Nghiên cứu can thiệp giáo dục đào tạo lại kỹ năng BLS.',
    researchField: 'Điều dưỡng',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'CẢI_TIẾN_KỸ_THUẬT',
    principalInvestigatorId: 'user-14',
    principalInvestigatorName: 'ThS. Đặng Thị Kim Oanh',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '01/06/2026',
    endDate: '30/11/2026',
    estimatedBudget: 20000000,
    approvedBudget: 0,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 0,
    status: 'DRAFT',
    proposalStatus: 'SUBMITTED',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '15/01/2026',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-14',
    projectCode: 'DT-2025-014',
    proposalCode: 'DX-2025-014',
    title: 'Xác định căn nguyên vi khuẩn gây viêm phổi bệnh viện và mô hình nhạy cảm kháng sinh',
    summary: 'Theo dõi 200 trường hợp VAP tại ICU.',
    researchField: 'Vi sinh',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'DỊCH_TỄ_HỌC',
    principalInvestigatorId: 'user-13',
    principalInvestigatorName: 'TS.BS. Phan Quỳnh Nga',
    departmentId: 'dept-04',
    departmentName: 'Khoa Hóa sinh - Huyết học - Vi sinh',
    startDate: '01/05/2025',
    endDate: '30/04/2026',
    estimatedBudget: 75000000,
    approvedBudget: 70000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 60,
    status: 'IN_PROGRESS',
    proposalStatus: 'VALID',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '10/01/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-15',
    projectCode: 'DT-2024-015',
    proposalCode: 'DX-2024-015',
    title: 'Đánh giá chi phí điều trị đợt cấp bệnh phổi tắc nghẽn mạn tính nội trú',
    summary: 'Phân tích gánh nặng kinh tế y tế trên 350 lượt bệnh nhân.',
    researchField: 'Dược lâm sàng',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'QUẢN_LÝ_Y_TẾ',
    principalInvestigatorId: 'user-12',
    principalInvestigatorName: 'DSCKII. Bùi Thanh Tùng',
    departmentId: 'dept-05',
    departmentName: 'Khoa Dược lâm sàng',
    startDate: '01/01/2024',
    endDate: '31/12/2024',
    estimatedBudget: 40000000,
    approvedBudget: 35000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 100,
    status: 'ARCHIVED',
    proposalStatus: 'VALID',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '10/12/2023',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-16',
    proposalCode: 'DX-2026-016',
    title: 'Khảo sát nồng độ Troponin T hs ở bệnh nhân suy thận mạn lọc máu chu kỳ không có triệu chứng mạch vành',
    summary: 'Đánh giá điểm cắt chẩn đoán hội chứng vành cấp ở bệnh nhân ESRD.',
    researchField: 'Tim mạch',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-01',
    principalInvestigatorName: 'BS.CKII. Nguyễn Văn An',
    departmentId: 'dept-01',
    departmentName: 'Khoa Tim mạch Can thiệp',
    startDate: '01/05/2026',
    endDate: '30/04/2027',
    estimatedBudget: 60000000,
    approvedBudget: 0,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 0,
    status: 'DRAFT',
    proposalStatus: 'UNDER_ADMIN_REVIEW',
    ethicsRequired: true,
    ethicsStatus: 'DOSSIER_SUBMITTED',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '18/01/2026',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-17',
    projectCode: 'DT-2025-017',
    proposalCode: 'DX-2025-017',
    title: 'Nghiên cứu tác dụng không mong muốn của phác đồ hóa trị AC-T trên bệnh nhân ung thư vú',
    summary: 'Ghi nhận độc tính huyết học và tiêu hóa trên 80 bệnh nhân.',
    researchField: 'Ung bướu',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-03',
    principalInvestigatorName: 'TS.BS. Lê Văn Cường',
    departmentId: 'dept-03',
    departmentName: 'Khoa Ung bướu & Xạ trị',
    startDate: '01/07/2025',
    endDate: '30/06/2026',
    estimatedBudget: 55000000,
    approvedBudget: 50000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 45,
    status: 'IN_PROGRESS',
    proposalStatus: 'VALID',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    registrationRoundId: 'round-2025-02',
    registrationRoundName: 'Đợt 2 Năm 2025',
    createdAt: '10/06/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-18',
    projectCode: 'DT-2025-018',
    proposalCode: 'DX-2025-018',
    title: 'Ứng dụng phần mềm nhắc nhở uống thuốc trên điện thoại thông minh ở bệnh nhân tăng huyết áp',
    summary: 'Nghiên cứu thử nghiệm lâm sàng ngẫu nhiên có đối chứng.',
    researchField: 'Cải tiến kỹ thuật',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'CẢI_TIẾN_KỸ_THUẬT',
    principalInvestigatorId: 'user-01',
    principalInvestigatorName: 'BS.CKII. Nguyễn Văn An',
    departmentId: 'dept-01',
    departmentName: 'Khoa Tim mạch Can thiệp',
    startDate: '01/09/2025',
    endDate: '31/08/2026',
    estimatedBudget: 40000000,
    approvedBudget: 35000000,
    fundingSource: 'TỰ_TÚC',
    progressPercentage: 30,
    status: 'IN_PROGRESS',
    proposalStatus: 'VALID',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    registrationRoundId: 'round-2025-02',
    registrationRoundName: 'Đợt 2 Năm 2025',
    createdAt: '01/08/2025',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-19',
    proposalCode: 'DX-2026-019',
    title: 'Khảo sát kiến thức phòng ngừa loét tỳ đè của người chăm sóc bệnh nhân tai biến mạch máu não',
    summary: 'Nghiên cứu mô tả cắt ngang trên 120 người chăm sóc chính.',
    researchField: 'Điều dưỡng',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'CAN_THIỆP_CỘNG_ĐỒNG',
    principalInvestigatorId: 'user-14',
    principalInvestigatorName: 'ThS. Đặng Thị Kim Oanh',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '01/05/2026',
    endDate: '31/10/2026',
    estimatedBudget: 18000000,
    approvedBudget: 0,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 0,
    status: 'DRAFT',
    proposalStatus: 'DRAFT',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '20/01/2026',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
  {
    id: 'proj-20',
    projectCode: 'DT-2024-020',
    proposalCode: 'DX-2024-020',
    title: 'Đánh giá độ thanh thải Creatinine ước tính theo các công thức Cockcroft-Gault, MDRD và CKD-EPI',
    summary: 'So sánh với độ thanh thải Creatinine nước tiểu 24 giờ ở bệnh nhân ĐTĐ type 2.',
    researchField: 'Hóa sinh',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-13',
    principalInvestigatorName: 'TS.BS. Phan Quỳnh Nga',
    departmentId: 'dept-04',
    departmentName: 'Khoa Hóa sinh - Huyết học - Vi sinh',
    startDate: '01/03/2024',
    endDate: '28/02/2025',
    estimatedBudget: 45000000,
    approvedBudget: 40000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    progressPercentage: 100,
    status: 'ARCHIVED',
    proposalStatus: 'VALID',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '15/01/2024',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: [],
    statusHistory: [],
  },
];

// ==========================================
// 5. HỘI ĐỒNG XÉT DUYỆT & NGHIỆM THU
// ==========================================
export const SEED_COUNCILS: Council[] = [
  {
    id: 'council-01',
    code: 'HD-XD-2026-01',
    name: 'Hội đồng Khoa học xét duyệt Đề cương Đợt 1 Năm 2026 (Khối Nội - Tim mạch - Hồi sức)',
    type: 'PROPOSAL_REVIEW',
    projectIds: ['proj-04', 'proj-05'],
    meetingDate: '2026-02-15 08:30',
    location: 'Phòng họp Giao ban số 1, Tầng 3 Nhà A',
    minPassRatio: 0.6, // 60% phiếu tán thành
    status: 'ESTABLISHED',
    members: [
      {
        id: 'cm-01',
        councilId: 'council-01',
        userId: 'user-05',
        userFullName: 'PGS.TS.BS. Phạm Đức Dũng',
        academicTitle: 'PGS.TS.BS',
        departmentName: 'Khoa Tim mạch',
        roleInCouncil: 'CHỦ_TỊCH',
        hasConflictOfInterest: false,
        evaluationSubmitted: true,
      },
      {
        id: 'cm-02',
        councilId: 'council-01',
        userId: 'user-07',
        userFullName: 'BS.CKI. Đỗ Bích Ngọc',
        academicTitle: 'BS.CKI',
        departmentName: 'Phòng NCKH',
        roleInCouncil: 'THƯ_KÝ',
        hasConflictOfInterest: false,
        evaluationSubmitted: true,
      },
      {
        id: 'cm-03',
        councilId: 'council-01',
        userId: 'user-06',
        userFullName: 'TS.BS. Hoàng Minh Tuấn',
        academicTitle: 'TS.BS',
        departmentName: 'Khoa Hồi sức tích cực',
        roleInCouncil: 'PHẢN_BIỆN_1',
        hasConflictOfInterest: false,
        evaluationSubmitted: false,
      },
      {
        id: 'cm-04',
        councilId: 'council-01',
        userId: 'user-15',
        userFullName: 'PGS.TS.BS. Ngô Gia Tiến',
        academicTitle: 'PGS.TS.BS',
        departmentName: 'Khoa Ngoại',
        roleInCouncil: 'PHẢN_BIỆN_2',
        hasConflictOfInterest: false,
        evaluationSubmitted: false,
      },
      {
        id: 'cm-05',
        councilId: 'council-01',
        userId: 'user-13',
        userFullName: 'TS.BS. Phan Quỳnh Nga',
        academicTitle: 'TS.BS',
        departmentName: 'Khoa Xét nghiệm',
        roleInCouncil: 'ỦY_VIÊN',
        hasConflictOfInterest: false,
        evaluationSubmitted: false,
      },
    ],
  },
  {
    id: 'council-02',
    code: 'HD-NT-2025-01',
    name: 'Hội đồng Đánh giá Nghiệm thu Đề tài Cấp cơ sở Năm 2025 (Chuyên ngành Can thiệp & Ngoại)',
    type: 'ACCEPTANCE_REVIEW',
    projectIds: ['proj-08', 'proj-11'],
    meetingDate: '2025-07-10 14:00',
    location: 'Hội trường Bệnh viện',
    minPassRatio: 0.6,
    status: 'CONCLUDED',
    members: [
      {
        id: 'cm-06',
        councilId: 'council-02',
        userId: 'user-05',
        userFullName: 'PGS.TS.BS. Phạm Đức Dũng',
        academicTitle: 'PGS.TS.BS',
        departmentName: 'Khoa Tim mạch',
        roleInCouncil: 'CHỦ_TỊCH',
        hasConflictOfInterest: false,
        evaluationSubmitted: true,
      },
      {
        id: 'cm-07',
        councilId: 'council-02',
        userId: 'user-07',
        userFullName: 'BS.CKI. Đỗ Bích Ngọc',
        academicTitle: 'BS.CKI',
        departmentName: 'Phòng NCKH',
        roleInCouncil: 'THƯ_KÝ',
        hasConflictOfInterest: false,
        evaluationSubmitted: true,
      },
    ],
  },
];
