import {
  Department,
  User,
  RegistrationRound,
  ResearchProject,
  Council,
  WorkflowPolicy,
  Decision,
} from '@/lib/types';

// ==========================================
// 0. CHÍNH SÁCH QUY TRÌNH (WORKFLOW POLICIES)
// ==========================================
export const SEED_WORKFLOW_POLICIES: WorkflowPolicy[] = [
  {
    id: 'policy-a',
    code: 'RICH.QT01.CO_SO',
    name: 'Chính sách Đề tài Cấp cơ sở (BV Nhi TW)',
    version: 'v2018.1',
    effectiveFrom: '2018-05-01',
    reportingIntervalMonths: 3,
    minDurationMonths: 6,
    maxDurationMonths: 12,
    maxExtensionsAllowed: 2,
    extensionDurationMonths: 3,
    requiresScientificReview: true,
    requiresEthicsReview: true,
    ethicsReviewMode: 'SEPARATE', // Luồng đạo đức riêng; cách triển khai thực tế vẫn do policy bệnh viện quyết định
    acceptanceMode: 'INTERNAL',
    requiredDocumentsByStep: {
      1: [{ type: 'PROPOSAL_FORM', label: 'Phiếu đề xuất đề tài (BM1)', required: true }],
      3: [{ type: 'DETAILED_OUTLINE', label: 'Thuyết minh đề cương chi tiết (BM2)', required: true }],
      5: [{ type: 'EXPLANATION_LETTER', label: 'Biên bản giải trình chỉnh sửa (BM7)', required: true }],
      9: [{ type: 'PROGRESS_REPORT_DOC', label: 'Báo cáo định kỳ tiến độ (BM9)', required: true }],
      10: [{ type: 'ACCEPTANCE_DOSSIER', label: 'Báo cáo kết quả nghiệm thu (BM11)', required: true }],
      12: [{ type: 'EXPLANATION_LETTER', label: 'Biên bản giải trình sau nghiệm thu (BM16)', required: true }]
    }
  },
  {
    id: 'policy-b',
    code: 'RICH.QT01.HOC_VIEN',
    name: 'Chính sách Nghiên cứu Học viên / Cao học / Nội trú',
    version: 'v2018.2',
    effectiveFrom: '2018-05-01',
    reportingIntervalMonths: 1, // Báo cáo hàng tháng
    minDurationMonths: 3,
    maxDurationMonths: 12,
    maxExtensionsAllowed: 1,
    extensionDurationMonths: 3,
    requiresScientificReview: true,
    requiresEthicsReview: true,
    ethicsReviewMode: 'SEPARATE', // Hội đồng Đạo đức riêng
    acceptanceMode: 'EXTERNAL', // Nghiệm thu tại cơ sở đào tạo ngoại viện
    requiredDocumentsByStep: {
      1: [
        { type: 'PROPOSAL_FORM', label: 'Giấy giới thiệu từ cơ sở đào tạo', required: true },
        { type: 'DETAILED_OUTLINE', label: 'Đề cương chi tiết ban đầu', required: true }
      ],
      3: [{ type: 'DETAILED_OUTLINE', label: 'Thuyết minh đề cương hoàn chỉnh', required: true }],
      6: [{ type: 'ETHICS_DOSSIER', label: 'Hồ sơ thẩm định đạo đức riêng', required: true }],
      9: [{ type: 'PROGRESS_REPORT_DOC', label: 'Báo cáo tiến độ hàng tháng', required: true }],
      10: [{ type: 'OTHER', label: 'Bản sao tóm tắt kết quả nghiệm thu', required: true }]
    }
  },
  {
    id: 'policy-c',
    code: 'QTQL.NC2.1.1.NHA_NUOC',
    name: 'Chính sách Đề tài cấp Bộ / cấp Nhà nước',
    version: 'v2025.1',
    effectiveFrom: '2025-01-01',
    reportingIntervalMonths: 6,
    minDurationMonths: 12,
    maxDurationMonths: 36,
    maxExtensionsAllowed: 1,
    extensionDurationMonths: 6,
    requiresScientificReview: true,
    requiresEthicsReview: true,
    ethicsReviewMode: 'SEPARATE',
    acceptanceMode: 'INTERNAL',
    requiredDocumentsByStep: {
      1: [{ type: 'PROPOSAL_FORM', label: 'Phiếu đề xuất cấp Bộ/Nhà nước', required: true }],
      3: [{ type: 'DETAILED_OUTLINE', label: 'Thuyết minh đề cương chi tiết', required: true }],
      6: [{ type: 'ETHICS_DOSSIER', label: 'Quyết định thông qua HĐ đạo đức riêng', required: true }],
      9: [{ type: 'PROGRESS_REPORT_DOC', label: 'Báo cáo định kỳ 6 tháng', required: true }],
      10: [{ type: 'ACCEPTANCE_DOSSIER', label: 'Hồ sơ nghiệm thu cấp Bộ/Nhà nước', required: true }]
    }
  }
];

// ==========================================
// 10. DECISIONS MOCK DATA
// ==========================================
export const SEED_DECISIONS: Decision[] = [
  // Đề tài đang thực hiện: Quyết định giao thực hiện đã ban hành
  {
    id: 'dec-01',
    type: 'ASSIGNMENT',
    status: 'ISSUED',
    projectId: 'proj-01',
    decisionNumber: '128/QĐ-BV',
    issuedDate: '2025-03-25T00:00:00+07:00',
    signedBy: 'GS.TS.BS. Vũ Đình Khoa',
    signedDate: '2025-03-24T00:00:00+07:00',
    signedFile: 'qd_128_giao_thuc_hien_proj01.pdf',
    createdAt: '2025-03-20T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec01-1',
        decisionId: 'dec-01',
        action: 'DRAFT_CREATED',
        toStatus: 'DRAFT',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2025-03-20T09:00:00+07:00',
      },
      {
        id: 'hist-dec01-2',
        decisionId: 'dec-01',
        action: 'SUBMITTED_FOR_SIGNATURE',
        fromStatus: 'DRAFT',
        toStatus: 'PENDING_SIGNATURE',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2025-03-21T10:00:00+07:00',
      },
      {
        id: 'hist-dec01-3',
        decisionId: 'dec-01',
        action: 'SIGNED',
        fromStatus: 'PENDING_SIGNATURE',
        toStatus: 'SIGNED',
        actorId: 'user-10',
        actorName: 'GS.TS.BS. Vũ Đình Khoa',
        actorRole: 'DIRECTOR',
        timestamp: '2025-03-24T15:00:00+07:00',
      },
      {
        id: 'hist-dec01-4',
        decisionId: 'dec-01',
        action: 'ISSUED',
        fromStatus: 'SIGNED',
        toStatus: 'ISSUED',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2025-03-25T08:00:00+07:00',
      },
    ],
  },

  // Đề tài đã đủ gate và đang chờ giao thực hiện: có dự thảo nhưng chưa trình ký
  {
    id: 'dec-06',
    type: 'ASSIGNMENT',
    status: 'DRAFT',
    projectId: 'proj-06',
    createdAt: '2026-02-21T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec06-1',
        decisionId: 'dec-06',
        action: 'DRAFT_CREATED',
        toStatus: 'DRAFT',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2026-02-21T09:00:00+07:00',
      },
    ],
  },

  // Các đề tài đang/đã triển khai đều phải có QĐ giao thực hiện đã ban hành
  {
    id: 'dec-07',
    type: 'ASSIGNMENT',
    status: 'ISSUED',
    projectId: 'proj-07',
    decisionNumber: '95/QĐ-BV',
    issuedDate: '2025-02-25T00:00:00+07:00',
    signedBy: 'GS.TS.BS. Vũ Đình Khoa',
    signedDate: '2025-02-24T00:00:00+07:00',
    signedFile: 'qd_95_giao_thuc_hien_proj07.pdf',
    createdAt: '2025-02-20T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec07-1',
        decisionId: 'dec-07',
        action: 'ISSUED',
        fromStatus: 'SIGNED',
        toStatus: 'ISSUED',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2025-02-25T08:00:00+07:00',
      },
    ],
  },
  {
    id: 'dec-08',
    type: 'ASSIGNMENT',
    status: 'ISSUED',
    projectId: 'proj-08',
    decisionNumber: '45/QĐ-BV',
    issuedDate: '2025-02-20T00:00:00+07:00',
    signedBy: 'GS.TS.BS. Vũ Đình Khoa',
    signedDate: '2025-02-19T00:00:00+07:00',
    signedFile: 'qd_45_giao_thuc_hien_proj08.pdf',
    createdAt: '2025-02-15T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec08-1',
        decisionId: 'dec-08',
        action: 'ISSUED',
        fromStatus: 'SIGNED',
        toStatus: 'ISSUED',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2025-02-20T08:00:00+07:00',
      },
    ],
  },
  {
    id: 'dec-09-assignment',
    type: 'ASSIGNMENT',
    status: 'ISSUED',
    projectId: 'proj-09',
    decisionNumber: '38/QĐ-BV',
    issuedDate: '2024-02-15T00:00:00+07:00',
    signedBy: 'GS.TS.BS. Vũ Đình Khoa',
    signedDate: '2024-02-14T00:00:00+07:00',
    createdAt: '2024-02-10T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec09a-1',
        decisionId: 'dec-09-assignment',
        action: 'ISSUED',
        fromStatus: 'SIGNED',
        toStatus: 'ISSUED',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2024-02-15T08:00:00+07:00',
      },
    ],
  },
  {
    id: 'dec-09-recognition',
    type: 'RECOGNITION',
    status: 'ISSUED',
    projectId: 'proj-09',
    decisionNumber: '312/QĐ-BV',
    issuedDate: '2025-01-20T00:00:00+07:00',
    signedBy: 'GS.TS.BS. Vũ Đình Khoa',
    signedDate: '2025-01-19T00:00:00+07:00',
    signedFile: 'qd_312_cong_nhan_proj09.pdf',
    createdAt: '2025-01-15T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec09r-1',
        decisionId: 'dec-09-recognition',
        action: 'ISSUED',
        fromStatus: 'SIGNED',
        toStatus: 'ISSUED',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2025-01-20T08:00:00+07:00',
      },
    ],
  },
  {
    id: 'dec-10-assignment',
    type: 'ASSIGNMENT',
    status: 'ISSUED',
    projectId: 'proj-10',
    decisionNumber: '51/QĐ-BV',
    issuedDate: '2024-02-25T00:00:00+07:00',
    signedBy: 'GS.TS.BS. Vũ Đình Khoa',
    signedDate: '2024-02-24T00:00:00+07:00',
    createdAt: '2024-02-20T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec10a-1',
        decisionId: 'dec-10-assignment',
        action: 'ISSUED',
        fromStatus: 'SIGNED',
        toStatus: 'ISSUED',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2024-02-25T08:00:00+07:00',
      },
    ],
  },
  {
    id: 'dec-10-recognition',
    type: 'RECOGNITION',
    status: 'ISSUED',
    projectId: 'proj-10',
    decisionNumber: '146/QĐ-BV',
    issuedDate: '2025-03-10T00:00:00+07:00',
    signedBy: 'GS.TS.BS. Vũ Đình Khoa',
    signedDate: '2025-03-09T00:00:00+07:00',
    createdAt: '2025-03-05T09:00:00+07:00',
    createdBy: 'user-04',
    history: [
      {
        id: 'hist-dec10r-1',
        decisionId: 'dec-10-recognition',
        action: 'ISSUED',
        fromStatus: 'SIGNED',
        toStatus: 'ISSUED',
        actorId: 'user-04',
        actorName: 'ThS. Lê Hoàng Long',
        actorRole: 'RESEARCH_OFFICE',
        timestamp: '2025-03-10T08:00:00+07:00',
      },
    ],
  },
];

// ==========================================
// 1. DANH MỤC KHOA / PHÒNG (8 KHOA/PHÒNG)
// ==========================================
export const SEED_DEPARTMENTS: Department[] = [
  { id: 'dept-01', code: 'TM', name: 'Khoa Tim mạch Can thiệp', type: 'CLINICAL' },
  { id: 'dept-02', code: 'HSTC', name: 'Khoa Hồi sức tích cực - Chống độc', type: 'CLINICAL' },
  { id: 'dept-03', code: 'UB', name: 'Khoa Ung bướu & Xạ trị', type: 'CLINICAL' },
  { id: 'dept-04', code: 'XN', name: 'Khoa Hóa sinh - Huyết học - Vi sinh', type: 'SUB_CLINICAL' },
  { id: 'dept-05', code: 'DL', name: 'Khoa Dược lâm sàng', type: 'SUB_CLINICAL' },
  { id: 'dept-06', code: 'NCKH', name: 'Phòng Quản lý NCKH & Đào tạo', type: 'ADMINISTRATIVE' },
  { id: 'dept-07', code: 'TCKT', name: 'Phòng Tài chính - Kế toán', type: 'ADMINISTRATIVE' },
  { id: 'dept-08', code: 'BGD', name: 'Ban Giám đốc Bệnh viện', type: 'ADMINISTRATIVE' },
];

// ==========================================
// 2. TÀI KHOẢN NGƯỜI DÙNG DEMO (15 USERS, 8 VAI TRÒ)
// ==========================================
export const SEED_USERS: User[] = [
  {
    id: 'user-01',
    email: 'researcher1@hospital.gov.vn',
    fullName: 'BS.CKII. Nguyễn Văn An',
    role: 'RESEARCHER',
    departmentId: 'dept-01',
    phone: '0912345671',
    academicTitle: 'BS.CKII',
    degree: 'Bác sĩ chuyên khoa II Tim mạch',
  },
  {
    id: 'user-02',
    email: 'researcher2@hospital.gov.vn',
    fullName: 'ThS.BS. Trần Thị Mai',
    role: 'RESEARCHER',
    departmentId: 'dept-02',
    phone: '0912345672',
    academicTitle: 'ThS.BS',
    degree: 'Thạc sĩ Hồi sức cấp cứu',
  },
  {
    id: 'user-03',
    email: 'researcher3@hospital.gov.vn',
    fullName: 'TS.BS. Lê Văn Cường',
    role: 'RESEARCHER',
    departmentId: 'dept-03',
    phone: '0912345673',
    academicTitle: 'TS.BS',
    degree: 'Tiến sĩ Ung bướu',
  },
  {
    id: 'user-04',
    email: 'research_office@hospital.gov.vn',
    fullName: 'ThS. Lê Hoàng Long',
    role: 'RESEARCH_OFFICE',
    departmentId: 'dept-06',
    phone: '0912345674',
    academicTitle: 'ThS',
    degree: 'Chuyên viên Quản lý NCKH',
  },
  {
    id: 'user-05',
    email: 'council_chair@hospital.gov.vn',
    fullName: 'PGS.TS.BS. Phạm Đức Dũng',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-01',
    phone: '0912345675',
    academicTitle: 'PGS.TS.BS',
    degree: 'Phó Giáo sư Tim mạch',
  },
  {
    id: 'user-06',
    email: 'council_member@hospital.gov.vn',
    fullName: 'TS.BS. Hoàng Minh Tuấn',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-02',
    phone: '0912345676',
    academicTitle: 'TS.BS',
    degree: 'Tiến sĩ Y khoa',
  },
  {
    id: 'user-07',
    email: 'council_sec@hospital.gov.vn',
    fullName: 'BS.CKI. Đỗ Bích Ngọc',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-06',
    phone: '0912345677',
    academicTitle: 'BS.CKI',
    degree: 'Thư ký Hội đồng Khoa học',
  },
  {
    id: 'user-08',
    email: 'ethics_office@hospital.gov.vn',
    fullName: 'TS.BS. Vũ Thị Hồng Hạnh',
    role: 'ETHICS_OFFICE',
    departmentId: 'dept-06',
    phone: '0912345678',
    academicTitle: 'TS.BS',
    degree: 'Thường trực Hội đồng Đạo đức Y sinh',
  },
  {
    id: 'user-09',
    email: 'finance_officer@hospital.gov.vn',
    fullName: 'CN. Nguyễn Thị Thu Hà',
    role: 'FINANCE_OFFICER',
    departmentId: 'dept-07',
    phone: '0912345679',
    academicTitle: 'Cử nhân',
    degree: 'Phụ trách Kế toán NCKH',
  },
  {
    id: 'user-10',
    email: 'director@hospital.gov.vn',
    fullName: 'GS.TS.BS. Vũ Đình Khoa',
    role: 'DIRECTOR',
    departmentId: 'dept-08',
    phone: '0912345680',
    academicTitle: 'GS.TS.BS',
    degree: 'Giám đốc Bệnh viện',
  },
  {
    id: 'user-11',
    email: 'admin@hospital.gov.vn',
    fullName: 'KS. Trịnh Quốc Bảo',
    role: 'ADMIN',
    departmentId: 'dept-06',
    phone: '0912345681',
    academicTitle: 'Kỹ sư CNTT',
    degree: 'Quản trị viên Hệ thống CRMS',
  },
  {
    id: 'user-12',
    email: 'pharmacist@hospital.gov.vn',
    fullName: 'DSCKII. Bùi Thanh Tùng',
    role: 'RESEARCHER',
    departmentId: 'dept-05',
    phone: '0912345682',
    academicTitle: 'DSCKII',
    degree: 'Dược sĩ chuyên khoa II',
  },
  {
    id: 'user-13',
    email: 'lab_head@hospital.gov.vn',
    fullName: 'TS.BS. Phan Quỳnh Nga',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-04',
    phone: '0912345683',
    academicTitle: 'TS.BS',
    degree: 'Trưởng khoa Xét nghiệm',
  },
  {
    id: 'user-14',
    email: 'nurse_head@hospital.gov.vn',
    fullName: 'ThS. Đặng Thị Kim Oanh',
    role: 'RESEARCHER',
    departmentId: 'dept-02',
    phone: '0912345684',
    academicTitle: 'ThS. Điều dưỡng',
    degree: 'Thạc sĩ Điều dưỡng Hồi sức',
  },
  {
    id: 'user-15',
    email: 'reviewer2@hospital.gov.vn',
    fullName: 'PGS.TS.BS. Ngô Gia Tiến',
    role: 'COUNCIL_MEMBER',
    departmentId: 'dept-03',
    phone: '0912345685',
    academicTitle: 'PGS.TS.BS',
    degree: 'Chuyên gia Phản biện Ngoại khoa',
  },
];

// ==========================================
// 3. ĐỢT ĐĂNG KÝ (3 ĐỢT)
// ==========================================
export const SEED_REGISTRATION_ROUNDS: RegistrationRound[] = [
  {
    id: 'round-2026-01',
    code: 'DOT-2026-01',
    name: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2026',
    year: 2026,
    startDate: '2026-01-05',
    endDate: '2026-03-31',
    targetAudience: 'Toàn thể Bác sĩ, Dược sĩ, Điều dưỡng và Kỹ thuật viên bệnh viện',
    status: 'OPEN',
    description: 'Ưu tiên các đề tài cải tiến quy trình lâm sàng, ứng dụng kỹ thuật mới và an toàn người bệnh.',
    maxBudget: 150000000,
    totalSubmissions: 8,
  },
  {
    id: 'round-2025-02',
    code: 'DOT-2025-02',
    name: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 2 Năm 2025',
    year: 2025,
    startDate: '2025-07-01',
    endDate: '2025-09-30',
    targetAudience: 'Cán bộ y tế các khoa Lâm sàng và Cận lâm sàng',
    status: 'CLOSED',
    description: 'Tập trung nghiên cứu dịch tễ học bệnh viện và quản lý kháng kháng sinh.',
    maxBudget: 100000000,
    totalSubmissions: 12,
  },
  {
    id: 'round-2025-01',
    code: 'DOT-2025-01',
    name: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2025',
    year: 2025,
    startDate: '2025-01-10',
    endDate: '2025-03-31',
    targetAudience: 'Toàn thể cán bộ nhân viên bệnh viện',
    status: 'CLOSED',
    description: 'Nghiên cứu khoa học thường niên phục vụ nâng cao chất lượng khám chữa bệnh.',
    maxBudget: 80000000,
    totalSubmissions: 15,
  },
  {
    id: 'round-2024-01',
    code: 'DOT-2024-01',
    name: 'Đợt đăng ký Đề tài NCKH Cấp cơ sở Đợt 1 Năm 2024',
    year: 2024,
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    targetAudience: 'Toàn thể cán bộ nhân viên bệnh viện',
    status: 'CLOSED',
    description: 'Nghiên cứu khoa học thường niên phục vụ nâng cao chất lượng khám chữa bệnh.',
    maxBudget: 80000000,
    totalSubmissions: 10,
  },
];

// ==========================================
// 4. DANH SÁCH 10 ĐỀ TÀI MẪU (Bao phủ đủ 10 State Machines)
// ==========================================
export const SEED_PROJECTS: ResearchProject[] = [
  // 1. Đang thực hiện (IN_PROGRESS) - Đạt chuẩn, có QĐ giao, mốc tiến độ chi tiết
  {
    id: 'proj-01',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    projectCode: 'DT-2025-001',
    proposalCode: 'DX-2025-001',
    title: 'Đánh giá hiệu quả can thiệp động mạch vành qua da ở bệnh nhân nhồi máu cơ tim cấp cao tuổi',
    summary: 'Nghiên cứu tiến cứu theo dõi 120 bệnh nhân trên 75 tuổi can thiệp stent phủ thuốc thế hệ mới.',
    researchField: 'Tim mạch',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-01',
    principalInvestigatorName: 'BS.CKII. Nguyễn Văn An',
    departmentId: 'dept-01',
    departmentName: 'Khoa Tim mạch Can thiệp',
    startDate: '2025-04-01',
    endDate: '2026-03-31',
    estimatedBudget: 95000000,
    approvedBudget: 85000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 65,
    urgencyExplanation: 'Nhồi máu cơ tim cấp (NMCTC) ở người cao tuổi có tỷ lệ tử vong và biến chứng cao. Can thiệp động mạch vành qua da (PCI) là phương pháp điều trị tái tưới máu tối ưu, tuy nhiên hiệu quả và tính an toàn ở đối tượng trên 75 tuổi tại bệnh viện cần được đánh giá cụ thể để tối ưu hóa quy trình lâm sàng.',
    expectedObjectives: '1. Đánh giá tỷ lệ thành công về mặt thủ thuật PCI ở bệnh nhân nhồi máu cơ tim cấp trên 75 tuổi.\n2. Khảo sát tỷ lệ biến cố tim mạch chính (MACE) trong vòng 30 ngày và 6 tháng sau can thiệp.',
    researchDesign: 'Nghiên cứu tiến cứu, mô tả cắt ngang có theo dõi dọc.',
    researchSubjects: 'Bệnh nhân từ 75 tuổi trở lên được chẩn đoán nhồi máu cơ tim cấp (có hoặc không có ST chênh lên) và có chỉ định can thiệp động mạch vành qua da tại Bệnh viện.',
    researchLocation: 'Khoa Tim mạch Can thiệp và Khoa Hồi sức tích cực - Chống độc.',
    selectionCriteria: '- Tuổi >= 75.\n- Được chẩn đoán xác định nhồi máu cơ tim cấp trong vòng 24 giờ đầu kể từ khi khởi phát triệu chứng.\n- Đồng ý tham gia nghiên cứu (ký phiếu đồng thuận).',
    exclusionCriteria: '- Nhồi máu cơ tim cấp có biến chứng sốc tim quá nặng không thể tiến hành PCI.\n- Bệnh nhân mắc các bệnh lý ác tính giai đoạn cuối hoặc suy đa tạng nặng.\n- Không đồng ý tham gia nghiên cứu.',
    recruitmentAndSampleCollection: 'Tuyển chọn bệnh nhân nhập viện tại Khoa Cấp cứu hoặc Khoa Tim mạch Can thiệp. Tiến hành làm các xét nghiệm cận lâm sàng, chụp và can thiệp động mạch vành theo quy trình chuẩn. Theo dõi các chỉ số lâm sàng, xét nghiệm trong thời gian nằm viện và tái khám định kỳ sau 1, 3 và 6 tháng.',
    researchVariables: 'Tuổi, giới tính, tiền sử bệnh (tăng huyết áp, đái tháo đường, suy thận), đặc điểm tổn thương mạch vành (hẹp thân chung, nhiều nhánh), loại stent sử dụng, tỷ lệ tái thông, các biến cố chảy máu, MACE (tử vong, tái nhồi máu, đột quỵ).',
    sampleSizeEstimation: 'Áp dụng công thức tính cỡ mẫu ước tính tỷ lệ với p dự kiến khoảng 85%, sai số cho phép 8%, cỡ mẫu tối thiểu tính toán được là 77 bệnh nhân. Dự kiến tuyển chọn 120 bệnh nhân để bù đắp sai số mất dấu theo dõi.',
    studyTimeEstimation: '12 tháng (từ tháng 04/2025 đến tháng 03/2026).',
    expectedProducts: '- Báo cáo tổng kết đề tài NCKH cấp cơ sở.\n- 01 Bài báo đăng trên tạp chí y học uy tín.\n- Bộ số liệu nghiên cứu sạch.',
    hospitalApplication: 'Hoàn thiện và cải tiến quy trình can thiệp động mạch vành ở bệnh nhân cao tuổi tại Khoa Tim mạch Can thiệp, giúp giảm thiểu tai biến chảy máu và tăng tỷ lệ thành công của thủ thuật.',
    otherInfo: 'Không có.',
    status: 'IN_PROGRESS',
    proposalStatus: 'PROPOSAL_APPROVED',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    financeStatus: 'ACTIVE',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '2025-01-15',
    submittedAt: '2025-01-20',
    approvedAt: '2025-03-25',
    members: [
      {
        id: 'mem-01',
        projectId: 'proj-01',
        userId: 'user-01',
        fullName: 'BS.CKII. Nguyễn Văn An',
        academicRank: 'BS.CKII',
        unit: 'Khoa Tim mạch Can thiệp',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 50,
      },
      {
        id: 'mem-02',
        projectId: 'proj-01',
        userId: 'user-02',
        fullName: 'ThS.BS. Trần Thị Mai',
        academicRank: 'ThS.BS',
        unit: 'Khoa Hồi sức tích cực',
        roleInProject: 'THÀNH_VIÊN_CHÍNH',
        contributionPercentage: 30,
      },
    ],
    documents: [
      {
        id: 'doc-01',
        projectId: 'proj-01',
        documentType: 'DETAILED_OUTLINE',
        title: 'Đề cương chi tiết đề tài',
        currentVersion: 2,
        currentVersionId: 'ver-02',
        versions: [
          {
            id: 'ver-01',
            documentId: 'doc-01',
            version: 1,
            fileName: 'De_cuong_v1.pdf',
            fileSize: '2.4 MB',
            uploadedBy: 'user-01',
            uploadedByName: 'BS.CKII. Nguyễn Văn An',
            uploadedAt: '2025-01-20',
            downloadUrl: '#',
            isCurrent: false,
          },
          {
            id: 'ver-02',
            documentId: 'doc-01',
            version: 2,
            fileName: 'De_cuong_v2_chinh_sua.pdf',
            fileSize: '2.6 MB',
            uploadedBy: 'user-01',
            uploadedByName: 'BS.CKII. Nguyễn Văn An',
            uploadedAt: '2025-02-15',
            downloadUrl: '#',
            isCurrent: true,
          },
        ],
      },
    ],
    milestones: [
      {
        id: 'ms-01',
        projectId: 'proj-01',
        title: 'Thu thập bệnh nhân đợt 1 (60 ca)',
        description: 'Hoàn thiện hồ sơ bệnh án nghiên cứu và xét nghiệm nền cho 60 ca đầu tiên.',
        targetDate: '2025-08-30',
        actualDate: '2025-08-25',
        weightPercentage: 40,
        status: 'COMPLETED',
        deliverables: '60 phiếu thu thập số liệu có chữ ký xác nhận.',
        completionPercentage: 100,
      },
      {
        id: 'ms-02',
        projectId: 'proj-01',
        title: 'Thu thập bệnh nhân đợt 2 (60 ca) & Đánh giá 6 tháng',
        description: 'Thu thập đủ 120 ca và theo dõi biến cố tim mạch chính sau 6 tháng can thiệp.',
        targetDate: '2025-12-31',
        weightPercentage: 40,
        status: 'IN_PROGRESS',
        deliverables: 'Dữ liệu theo dõi 120 bệnh nhân.',
        completionPercentage: 50,
      },
      {
        id: 'ms-03',
        projectId: 'proj-01',
        title: 'Xử lý thống kê và Viết báo cáo tổng kết',
        description: 'Phân tích SPSS, viết báo cáo tổng kết đề tài và bài báo khoa học.',
        targetDate: '2026-03-31',
        weightPercentage: 20,
        status: 'NOT_STARTED',
        deliverables: 'Bản thảo Báo cáo tổng kết và bài báo nghiệm thu.',
        completionPercentage: 0,
      },
    ],
    progressReports: [
      {
        id: 'pr-01',
        projectId: 'proj-01',
        period: 'Kỳ 1 (6 tháng đầu)',
        reportingDate: '2025-09-15',
        workCompleted: 'Đã hoàn thành thu thập 60/120 bệnh nhân, hoàn thành xét nghiệm sinh hóa cơ bản.',
        resultsAchieved: 'Tỷ lệ can thiệp thành công 98.3%, không có tử vong nội viện trong nhóm can thiệp.',
        reportedCompletionPercentage: 50,
        nextPlan: 'Tiếp tục thu thập 60 bệnh nhân còn lại và tái khám định kỳ 6 tháng.',
        evidenceUrls: [{ name: 'Bao_cao_tien_do_ky_1.pdf', url: '#' }],
        status: 'APPROVED',
        reviewComment: 'Tiến độ thu thập số liệu tốt, đạt yêu cầu đề ra.',
        reviewedBy: 'user-04',
        reviewedAt: '2025-09-20',
      },
    ],
    changeRequests: [],
    ethicsApproval: {
      id: 'eth-01',
      projectId: 'proj-01',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: true,
        involvesNewInterventionsOrDrugs: true,
      },
      ethicsRequired: true,
      reviewType: 'FULL_BOARD',
      decisionNumber: 'GCN-ĐĐ-2025/012',
      approvalDate: '2025-02-28',
      expiryDate: '2026-02-28',
      status: 'ETHICS_APPROVED',
      notes: 'Đề tài tuân thủ đầy đủ GCP và bảo vệ quyền lợi người bệnh tham gia nghiên cứu.',
    },
    financialSummary: {
      id: 'fin-01',
      projectId: 'proj-01',
      fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
      estimatedBudget: 95000000,
      approvedBudget: 85000000,
      allocatedBudget: 42500000,
      disbursedBudget: 38000000,
      settledBudget: 0,
      refundableBudget: 0,
      status: 'ACTIVE',
      hasContract: true,
      notes: 'Đã tạm ứng đợt 1 (50% kinh phí phê duyệt).',
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-01'),
    statusHistory: [
      {
        id: 'h-01',
        projectId: 'proj-01',
        fromStatus: 'NONE',
        toStatus: 'DRAFT',
        changedBy: 'user-01',
        changedByName: 'BS.CKII. Nguyễn Văn An',
        userRole: 'RESEARCHER',
        changedAt: '2025-01-15',
        action: 'Tạo hồ sơ đề xuất đề tài mới',
      },
      {
        id: 'h-02',
        projectId: 'proj-01',
        fromStatus: 'DRAFT',
        toStatus: 'WAITING_ASSIGNMENT',
        changedBy: 'user-04',
        changedByName: 'ThS. Lê Hoàng Long',
        userRole: 'RESEARCH_OFFICE',
        changedAt: '2025-03-25',
        action: 'Hội đồng Khoa học thông qua đề cương',
      },
      {
        id: 'h-03',
        projectId: 'proj-01',
        fromStatus: 'WAITING_ASSIGNMENT',
        toStatus: 'IN_PROGRESS',
        changedBy: 'user-10',
        changedByName: 'GS.TS.BS. Vũ Đình Khoa',
        userRole: 'DIRECTOR',
        changedAt: '2025-04-01',
        action: 'Ban hành Quyết định giao thực hiện đề tài',
      },
    ],
  },

  // 2. Bản nháp (DRAFT) - Chủ nhiệm đang soạn thảo
  {
    id: 'proj-02',
    workflowPolicyId: 'policy-b',
    projectCategory: 'CAO_HOC',
    acceptanceAuthority: 'CO_SO_DAO_TAO',
    scientificReviewStatus: 'REQUIRED',
    proposalCode: 'DX-2026-002',
    title: 'Nghiên cứu tỷ lệ nhiễm vi khuẩn đa kháng thuốc tại Khoa Hồi sức tích cực năm 2026',
    summary: 'Khảo sát mô hình vi khuẩn học và mức độ nhạy cảm kháng sinh của các chủng Acinetobacter baumannii, Pseudomonas aeruginosa.',
    researchField: 'Hồi sức cấp cứu',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'DỊCH_TỄ_HỌC',
    principalInvestigatorId: 'user-02',
    principalInvestigatorName: 'ThS.BS. Trần Thị Mai',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '2026-05-01',
    endDate: '2027-04-30',
    estimatedBudget: 60000000,
    approvedBudget: 60000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 0,
    status: 'DRAFT',
    proposalStatus: 'DRAFT',
    ethicsRequired: true,
    ethicsStatus: 'SCREENING_IN_PROGRESS',
    financeStatus: 'PENDING',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '2026-01-10',
    members: [
      {
        id: 'mem-03',
        projectId: 'proj-02',
        userId: 'user-02',
        fullName: 'ThS.BS. Trần Thị Mai',
        academicRank: 'ThS.BS',
        unit: 'Khoa Hồi sức tích cực',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 70,
      },
    ],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    ethicsApproval: {
      id: 'eth-02',
      projectId: 'proj-02',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: true,
        involvesNewInterventionsOrDrugs: false,
      },
      ethicsRequired: true,
      status: 'SCREENING_IN_PROGRESS',
      notes: 'Dữ liệu mẫu phục vụ kiểm thử luồng sàng lọc đạo đức.',
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-02'),
    statusHistory: [
      {
        id: 'h-04',
        projectId: 'proj-02',
        fromStatus: 'NONE',
        toStatus: 'DRAFT',
        changedBy: 'user-02',
        changedByName: 'ThS.BS. Trần Thị Mai',
        userRole: 'RESEARCHER',
        changedAt: '2026-01-10',
        action: 'Tạo bản nháp đề xuất đề tài',
      },
    ],
  },

  // 3. Đã nộp hồ sơ (UNDER_REVIEW / SUBMITTED) - Chờ Phòng NCKH thẩm định hành chính
  {
    id: 'proj-03',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    proposalCode: 'DX-2026-003',
    title: 'Khảo sát tình hình sử dụng thuốc kháng sinh dự phòng trong phẫu thuật tiêu hóa',
    summary: 'Đánh giá tính hợp lý trong chỉ định, thời điểm dùng và thời gian kéo dài kháng sinh dự phòng theo phác đồ bệnh viện.',
    researchField: 'Dược lâm sàng',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'QUẢN_LÝ_Y_TẾ',
    principalInvestigatorId: 'user-12',
    principalInvestigatorName: 'DSCKII. Bùi Thanh Tùng',
    departmentId: 'dept-05',
    departmentName: 'Khoa Dược lâm sàng',
    startDate: '2026-05-01',
    endDate: '2026-10-31',
    estimatedBudget: 45000000,
    approvedBudget: 45000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 0,
    status: 'SUBMITTED',
    proposalStatus: 'SUBMITTED',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    financeStatus: 'PENDING',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '2026-01-18',
    submittedAt: '2026-01-22',
    members: [
      {
        id: 'mem-04',
        projectId: 'proj-03',
        userId: 'user-12',
        fullName: 'DSCKII. Bùi Thanh Tùng',
        academicRank: 'DSCKII',
        unit: 'Khoa Dược lâm sàng',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 60,
      },
    ],
    documents: [
      {
        id: 'doc-02',
        projectId: 'proj-03',
        documentType: 'PROPOSAL_FORM',
        title: 'Đơn đăng ký đề tài NCKH',
        currentVersion: 1,
        currentVersionId: 'ver-03',
        versions: [
          {
            id: 'ver-03',
            documentId: 'doc-02',
            version: 1,
            fileName: 'Don_dang_ky_DX2026003.pdf',
            fileSize: '1.2 MB',
            uploadedBy: 'user-12',
            uploadedByName: 'DSCKII. Bùi Thanh Tùng',
            uploadedAt: '2026-01-22',
            downloadUrl: '#',
            isCurrent: true,
          },
        ],
      },
    ],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-03'),
    statusHistory: [
      {
        id: 'h-05',
        projectId: 'proj-03',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        changedBy: 'user-12',
        changedByName: 'DSCKII. Bùi Thanh Tùng',
        userRole: 'RESEARCHER',
        changedAt: '2026-01-22',
        action: 'Nộp chính thức hồ sơ đề xuất',
      },
    ],
  },

  // 4. Cần bổ sung hồ sơ (UNDER_REVIEW / REVISION_REQUIRED) - Phòng NCKH yêu cầu sửa
  {
    id: 'proj-04',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    proposalCode: 'DX-2026-004',
    title: 'Ứng dụng thang điểm NEWS2 trong cảnh báo sớm suy hô hấp ở bệnh nhân thở máy',
    summary: 'Nghiên cứu giá trị dự báo đặt lại nội khí quản và tử vong tại Khoa Hồi sức cấp cứu.',
    researchField: 'Điều dưỡng',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'CẢI_TIẾN_KỸ_THUẬT',
    principalInvestigatorId: 'user-14',
    principalInvestigatorName: 'ThS. Đặng Thị Kim Oanh',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '2026-05-01',
    endDate: '2027-04-30',
    estimatedBudget: 35000000,
    approvedBudget: 35000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 0,
    status: 'SUBMITTED',
    proposalStatus: 'REVISION_REQUIRED',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_REVISION_REQUIRED',
    financeStatus: 'PENDING',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '2026-01-12',
    submittedAt: '2026-01-15',
    members: [
      {
        id: 'mem-05',
        projectId: 'proj-04',
        userId: 'user-14',
        fullName: 'ThS. Đặng Thị Kim Oanh',
        academicRank: 'ThS. Điều dưỡng',
        unit: 'Khoa Hồi sức tích cực',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 80,
      },
    ],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    ethicsApproval: {
      id: 'eth-04',
      projectId: 'proj-04',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: false,
        involvesNewInterventionsOrDrugs: false,
      },
      ethicsRequired: true,
      reviewType: 'FULL_BOARD',
      dossierSubmittedDate: '2026-01-20',
      status: 'ETHICS_REVISION_REQUIRED',
      notes: 'Hồ sơ mẫu đang ở trạng thái yêu cầu bổ sung.',
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-04'),
    statusHistory: [
      {
        id: 'h-06',
        projectId: 'proj-04',
        fromStatus: 'SUBMITTED',
        toStatus: 'SUBMITTED',
        changedBy: 'user-04',
        changedByName: 'ThS. Lê Hoàng Long',
        userRole: 'RESEARCH_OFFICE',
        changedAt: '2026-01-25',
        action: 'Yêu cầu bổ sung dự toán chi tiết và phiếu đồng thuận người bệnh (ICF)',
        comment: 'Cần bổ sung chi tiết dự toán chi phí thu thập mẫu và Phiếu đồng thuận theo mẫu BM-03.',
      },
    ],
  },

  // 5. Hồ sơ hợp lệ, chờ Hội đồng (UNDER_REVIEW / VALID) - Đã phân công Hội đồng
  {
    id: 'proj-05',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    proposalCode: 'DX-2026-005',
    title: 'Khảo sát đột biến gen EGFR ở bệnh nhân ung thư phổi không tế bào nhỏ',
    summary: 'Nghiên cứu mối liên quan giữa tình trạng đột biến exon 19, 21 với đặc điểm lâm sàng và đáp ứng điều trị TKI.',
    researchField: 'Ung bướu',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-03',
    principalInvestigatorName: 'TS.BS. Lê Văn Cường',
    departmentId: 'dept-03',
    departmentName: 'Khoa Ung bướu & Xạ trị',
    startDate: '2026-05-01',
    endDate: '2027-04-30',
    estimatedBudget: 110000000,
    approvedBudget: 110000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 0,
    status: 'SUBMITTED',
    proposalStatus: 'UNDER_PROPOSAL_REVIEW',
    ethicsRequired: true,
    ethicsStatus: 'DOSSIER_SUBMITTED',
    financeStatus: 'PENDING',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '2026-01-10',
    submittedAt: '2026-01-16',
    members: [
      {
        id: 'mem-06',
        projectId: 'proj-05',
        userId: 'user-03',
        fullName: 'TS.BS. Lê Văn Cường',
        academicRank: 'TS.BS',
        unit: 'Khoa Ung bướu & Xạ trị',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 60,
      },
    ],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    ethicsApproval: {
      id: 'eth-05',
      projectId: 'proj-05',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: true,
        involvesNewInterventionsOrDrugs: false,
      },
      ethicsRequired: true,
      reviewType: 'FULL_BOARD',
      dossierSubmittedDate: '2026-01-29',
      status: 'DOSSIER_SUBMITTED',
      notes: 'Hồ sơ đạo đức đã nộp, chờ tiếp nhận/thẩm định.',
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-05'),
    statusHistory: [
      {
        id: 'h-07',
        projectId: 'proj-05',
        fromStatus: 'SUBMITTED',
        toStatus: 'SUBMITTED',
        changedBy: 'user-04',
        changedByName: 'ThS. Lê Hoàng Long',
        userRole: 'RESEARCH_OFFICE',
        changedAt: '2026-01-28',
        action: 'Thẩm định hồ sơ HỢP LỆ (Chuyển HĐ xét duyệt đề cương)',
      },
    ],
  },

  // 6. Đã duyệt đề cương, chờ Quyết định giao (APPROVED / WAITING_ASSIGNMENT)
  {
    id: 'proj-06',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    projectCode: 'DT-2026-006',
    proposalCode: 'DX-2026-006',
    title: 'Đánh giá giá trị của Troponin T hs trong phân tầng nguy cơ hội chứng vành cấp',
    summary: 'Nghiên cứu theo dõi biến cố tim mạch 30 ngày tại Khoa Cấp cứu và Tim mạch.',
    researchField: 'Tim mạch',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-01',
    principalInvestigatorName: 'BS.CKII. Nguyễn Văn An',
    departmentId: 'dept-01',
    departmentName: 'Khoa Tim mạch Can thiệp',
    startDate: '2026-05-01',
    endDate: '2027-04-30',
    estimatedBudget: 80000000,
    approvedBudget: 75000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 0,
    status: 'WAITING_ASSIGNMENT',
    proposalStatus: 'PROPOSAL_APPROVED',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    financeStatus: 'PENDING',
    registrationRoundId: 'round-2026-01',
    registrationRoundName: 'Đợt 1 Năm 2026',
    createdAt: '2026-01-08',
    submittedAt: '2026-01-12',
    approvedAt: '2026-02-20',
    members: [
      {
        id: 'mem-07',
        projectId: 'proj-06',
        userId: 'user-01',
        fullName: 'BS.CKII. Nguyễn Văn An',
        academicRank: 'BS.CKII',
        unit: 'Khoa Tim mạch Can thiệp',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 60,
      },
    ],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    ethicsApproval: {
      id: 'eth-06',
      projectId: 'proj-06',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: true,
        involvesNewInterventionsOrDrugs: false,
      },
      ethicsRequired: true,
      reviewType: 'FULL_BOARD',
      dossierSubmittedDate: '2026-02-05',
      decisionNumber: 'GCN-ĐĐ-2026/006',
      approvalDate: '2026-02-18',
      expiryDate: '2027-02-18',
      status: 'ETHICS_APPROVED',
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-06'),
    statusHistory: [
      {
        id: 'h-08',
        projectId: 'proj-06',
        fromStatus: 'SUBMITTED',
        toStatus: 'WAITING_ASSIGNMENT',
        changedBy: 'user-05',
        changedByName: 'PGS.TS.BS. Phạm Đức Dũng',
        userRole: 'COUNCIL_MEMBER',
        changedAt: '2026-02-20',
        action: 'Hội đồng Khoa học thông qua Đề cương',
      },
    ],
  },

  // 7. Đang thực hiện, có yêu cầu điều chỉnh gia hạn (IN_PROGRESS / EXTENSION_REQUESTED)
  {
    id: 'proj-07',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    projectCode: 'DT-2025-007',
    proposalCode: 'DX-2025-007',
    title: 'Khảo sát nồng độ Procalcitonin huyết thanh trong tiên lượng sốc nhiễm khuẩn',
    summary: 'Theo dõi động học PCT ngày 1, ngày 3, ngày 5 tại Khoa Hồi sức tích cực.',
    researchField: 'Hồi sức cấp cứu',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-02',
    principalInvestigatorName: 'ThS.BS. Trần Thị Mai',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '2025-03-01',
    endDate: '2026-02-28',
    estimatedBudget: 70000000,
    approvedBudget: 70000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 80,
    status: 'IN_PROGRESS',
    proposalStatus: 'PROPOSAL_APPROVED',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    financeStatus: 'ACTIVE',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '2025-01-10',
    submittedAt: '2025-01-18',
    approvedAt: '2025-02-25',
    members: [
      {
        id: 'mem-08',
        projectId: 'proj-07',
        userId: 'user-02',
        fullName: 'ThS.BS. Trần Thị Mai',
        academicRank: 'ThS.BS',
        unit: 'Khoa Hồi sức tích cực',
        roleInProject: 'CHỦ_NHIỆM',
        contributionPercentage: 70,
      },
    ],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [
      {
        id: 'cr-01',
        projectId: 'proj-07',
        type: 'EXTENSION',
        title: 'Đề nghị gia hạn thời gian thực hiện đề tài thêm 03 tháng',
        diffs: [
          {
            fieldName: 'Thời gian kết thúc',
            currentValue: '28/02/2026',
            proposedValue: '31/05/2026',
            reason: 'Cần bổ sung thêm cỡ mẫu xét nghiệm lặp lại ở nhóm bệnh nhân sốc nhiễm khuẩn biến chứng suy đa tạng.',
          },
        ],
        reason: 'Số lượng ca bệnh đáp ứng tiêu chuẩn chọn mẫu vào mùa đông tăng chậm hơn dự kiến.',
        status: 'SUBMITTED',
        submittedAt: '2026-01-15',
        submittedBy: 'user-02',
        submittedByName: 'ThS.BS. Trần Thị Mai',
      },
    ],
    ethicsApproval: {
      id: 'eth-07',
      projectId: 'proj-07',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: true,
        involvesNewInterventionsOrDrugs: false,
      },
      ethicsRequired: true,
      reviewType: 'FULL_BOARD',
      decisionNumber: 'GCN-ĐĐ-2025/021',
      approvalDate: '2025-02-20',
      expiryDate: '2026-05-31',
      status: 'ETHICS_APPROVED',
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-07'),
    statusHistory: [],
  },

  // 8. Chờ nghiệm thu (WAITING_ACCEPTANCE) - Đã nộp hồ sơ nghiệm thu
  {
    id: 'proj-08',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    projectCode: 'DT-2024-008',
    proposalCode: 'DX-2024-008',
    title: 'Đánh giá kết quả phẫu thuật nội soi cắt túi mật ở bệnh nhân viêm túi mật cấp',
    summary: 'Nghiên cứu tiến cứu trên 150 bệnh nhân phẫu thuật cấp cứu trong 72 giờ đầu.',
    researchField: 'Ngoại khoa',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-15',
    principalInvestigatorName: 'PGS.TS.BS. Ngô Gia Tiến',
    departmentId: 'dept-03',
    departmentName: 'Khoa Ung bướu & Xạ trị',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    estimatedBudget: 80000000,
    approvedBudget: 80000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 100,
    status: 'WAITING_ACCEPTANCE',
    proposalStatus: 'PROPOSAL_APPROVED',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    financeStatus: 'ACTIVE',
    registrationRoundId: 'round-2025-01',
    registrationRoundName: 'Đợt 1 Năm 2025',
    createdAt: '2025-01-10',
    submittedAt: '2025-01-15',
    approvedAt: '2025-02-20',
    completedAt: '2025-12-31',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    ethicsApproval: {
      id: 'eth-08',
      projectId: 'proj-08',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: false,
        involvesNewInterventionsOrDrugs: false,
      },
      ethicsRequired: true,
      reviewType: 'FULL_BOARD',
      decisionNumber: 'GCN-ĐĐ-2025/008',
      approvalDate: '2025-02-10',
      expiryDate: '2026-12-31',
      status: 'ETHICS_APPROVED',
    },
    acceptanceDossier: {
      id: 'acc-01',
      projectId: 'proj-08',
      submissionDate: '2026-01-10',
      productsSummary: '01 Báo cáo tổng kết hoàn chỉnh (120 trang), 01 bài báo công bố trên Tạp chí Y học Việt Nam.',
      productsCommitted: '01 Báo cáo tổng kết, 01 bài báo tạp chí chuyên ngành',
      productsActual: '01 Báo cáo tổng kết, 01 bài báo đã đăng Tạp chí Y học',
      claimedOverallCompletionPercentage: 100,
      evidenceUrls: [{ name: 'Bao_cao_tong_ket_nghiem_thu.pdf', url: '#' }],
      status: 'FORWARDED_TO_COUNCIL',
      checklistResults: {
        finalReportSubmitted: true,
        productsCompleted: true,
        evidenceValid: true,
        progressReportsCompleted: true,
        noPendingChangeRequests: true,
        ethicsValid: true,
        financeConditionMet: true,
        publicationsIfRequired: true,
      },
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-08'),
    statusHistory: [],
  },

  // 9. Đã nghiệm thu & Có QĐ công nhận (ACCEPTED / RECOGNIZED)
  {
    id: 'proj-09',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    projectCode: 'DT-2024-009',
    proposalCode: 'DX-2024-009',
    title: 'Khảo sát hiệu quả kiểm soát đường huyết bằng Insulin nền phối hợp ở bệnh nhân ĐTĐ type 2',
    summary: 'Nghiên cứu theo dõi chỉ số HbA1c và nguy cơ hạ đường huyết sau 6 tháng điều trị nội trú.',
    researchField: 'Nội tiết',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'NGHIÊN_CỨU_LÂM_SÀNG',
    principalInvestigatorId: 'user-01',
    principalInvestigatorName: 'BS.CKII. Nguyễn Văn An',
    departmentId: 'dept-01',
    departmentName: 'Khoa Tim mạch Can thiệp',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    estimatedBudget: 65000000,
    approvedBudget: 60000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 100,
    status: 'RECOGNIZED',
    proposalStatus: 'PROPOSAL_APPROVED',
    ethicsRequired: true,
    ethicsStatus: 'ETHICS_APPROVED',
    financeStatus: 'FINALIZED',
    registrationRoundId: 'round-2024-01',
    registrationRoundName: 'Đợt 1 Năm 2024',
    createdAt: '2024-01-05',
    submittedAt: '2024-01-12',
    approvedAt: '2024-02-15',
    completedAt: '2024-12-31',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    ethicsApproval: {
      id: 'eth-09',
      projectId: 'proj-09',
      screeningAnswers: {
        involvesHumanSubjects: true,
        involvesIdentifiableData: true,
        involvesBiologicalSamples: true,
        involvesNewInterventionsOrDrugs: false,
      },
      ethicsRequired: true,
      reviewType: 'FULL_BOARD',
      decisionNumber: 'GCN-ĐĐ-2024/009',
      approvalDate: '2024-02-10',
      expiryDate: '2025-02-10',
      status: 'ETHICS_APPROVED',
    },
    financialSummary: {
      id: 'fin-09',
      projectId: 'proj-09',
      fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
      estimatedBudget: 65000000,
      approvedBudget: 60000000,
      allocatedBudget: 60000000,
      disbursedBudget: 59500000,
      settledBudget: 59500000,
      refundableBudget: 500000,
      status: 'FINALIZED',
      hasContract: false,
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-09'),
    statusHistory: [],
  },

  // 10. Đã đóng tài chính và Lưu trữ dài hạn (CLOSED / ARCHIVED)
  {
    id: 'proj-10',
    workflowPolicyId: 'policy-a',
    projectCategory: 'CAP_CO_SO',
    acceptanceAuthority: 'BENH_VIEN',
    scientificReviewStatus: 'REQUIRED',
    projectCode: 'DT-2024-010',
    proposalCode: 'DX-2024-010',
    title: 'Đánh giá thực trạng tuân thủ vệ sinh tay của nhân viên y tế tại các khoa lâm sàng',
    summary: 'Nghiên cứu can thiệp quan sát 1,200 cơ hội vệ sinh tay trước và sau tập huấn an toàn người bệnh.',
    researchField: 'Kiểm soát nhiễm khuẩn',
    managementLevel: 'CẤP_CƠ_SỞ',
    projectType: 'CAN_THIỆP_CỘNG_ĐỒNG',
    principalInvestigatorId: 'user-14',
    principalInvestigatorName: 'ThS. Đặng Thị Kim Oanh',
    departmentId: 'dept-02',
    departmentName: 'Khoa Hồi sức tích cực - Chống độc',
    startDate: '2024-03-01',
    endDate: '2025-02-28',
    estimatedBudget: 40000000,
    approvedBudget: 40000000,
    fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
    reportedProgressPercentage: 100,
    status: 'ARCHIVED',
    proposalStatus: 'PROPOSAL_APPROVED',
    ethicsRequired: false,
    ethicsStatus: 'NOT_REQUIRED',
    financeStatus: 'CLOSED',
    registrationRoundId: 'round-2024-01',
    registrationRoundName: 'Đợt 1 Năm 2024',
    createdAt: '2024-01-15',
    submittedAt: '2024-01-20',
    approvedAt: '2024-02-25',
    completedAt: '2025-02-28',
    members: [],
    documents: [],
    milestones: [],
    progressReports: [],
    changeRequests: [],
    financialSummary: {
      id: 'fin-10',
      projectId: 'proj-10',
      fundingSource: 'NGÂN_SÁCH_BỆNH_VIỆN',
      estimatedBudget: 40000000,
      approvedBudget: 40000000,
      allocatedBudget: 40000000,
      disbursedBudget: 40000000,
      settledBudget: 40000000,
      refundableBudget: 0,
      status: 'CLOSED',
      hasContract: false,
    },
    decisions: SEED_DECISIONS.filter((decision) => decision.projectId === 'proj-10'),
    closure: {
      id: 'closure-10',
      projectId: 'proj-10',
      status: 'COMPLETED',
      items: [
        {
          code: 'FINAL_REPORT',
          label: 'Báo cáo hoàn thiện đã nộp',
          required: true,
          completed: true,
          completedAt: '2025-03-12',
          completedBy: 'user-04',
        },
        {
          code: 'DATA_ARCHIVE',
          label: 'Bộ dữ liệu nghiên cứu đã bàn giao',
          required: true,
          completed: true,
          completedAt: '2025-03-12',
          completedBy: 'user-04',
        },
        {
          code: 'LIBRARY_CONFIRMATION',
          label: 'Đã hoàn tất nộp lưu theo quy định',
          required: true,
          completed: true,
          completedAt: '2025-03-12',
          completedBy: 'user-04',
        },
      ],
      confirmedBy: 'user-04',
      confirmedByName: 'ThS. Lê Hoàng Long',
      confirmedAt: '2025-03-12',
    },
    statusHistory: [],
  },
];

// ==========================================
// 5. HỘI ĐỒNG XÉT DUYỆT & NGHIỆM THU
// ==========================================
export const SEED_COUNCILS: Council[] = [
  {
    id: 'council-01',
    code: 'HD-XD-2026-01',
    name: 'Hội đồng Khoa học xét duyệt Đề cương Đợt 1 Năm 2026 (Khối Nội - Tim mạch - Hồi sức)',
    type: 'PROPOSAL_REVIEW',
    projectIds: ['proj-05'],
    projectAssignments: [
      {
        projectId: 'proj-05',
        reviewerAssignments: [
          { reviewerId: 'user-06', reviewerName: 'TS.BS. Hoàng Minh Tuấn', reviewerOrder: 1 },
          { reviewerId: 'user-15', reviewerName: 'PGS.TS.BS. Ngô Gia Tiến', reviewerOrder: 2 }
        ],
        notes: 'Thẩm định kỹ thuật sinh học phân tử xét nghiệm EGFR',
      },
    ],
    minMembers: 3,
    requiredReviewerCount: 2,
    meetingDate: '2026-02-15T08:30:00+07:00',
    location: 'Phòng họp Giao ban số 1, Tầng 3 Nhà A',
    minPassRatio: 0.6,
    status: 'ESTABLISHED',
    members: [
      {
        id: 'cm-01',
        councilId: 'council-01',
        userId: 'user-05',
        userFullName: 'PGS.TS.BS. Phạm Đức Dũng',
        academicTitle: 'PGS.TS.BS',
        departmentName: 'Khoa Tim mạch Can thiệp',
        roleInCouncil: 'CHỦ_TỊCH',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-02',
        councilId: 'council-01',
        userId: 'user-07',
        userFullName: 'BS.CKI. Đỗ Bích Ngọc',
        academicTitle: 'BS.CKI',
        departmentName: 'Phòng Quản lý NCKH',
        roleInCouncil: 'THƯ_KÝ',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-03',
        councilId: 'council-01',
        userId: 'user-06',
        userFullName: 'TS.BS. Hoàng Minh Tuấn',
        academicTitle: 'TS.BS',
        departmentName: 'Khoa Hồi sức tích cực',
        roleInCouncil: 'PHẢN_BIỆN',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-04',
        councilId: 'council-01',
        userId: 'user-15',
        userFullName: 'PGS.TS.BS. Ngô Gia Tiến',
        academicTitle: 'PGS.TS.BS',
        departmentName: 'Khoa Ung bướu & Xạ trị',
        roleInCouncil: 'PHẢN_BIỆN',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-05',
        councilId: 'council-01',
        userId: 'user-13',
        userFullName: 'TS.BS. Phan Quỳnh Nga',
        academicTitle: 'TS.BS',
        departmentName: 'Khoa Hóa sinh - Huyết học - Vi sinh',
        roleInCouncil: 'ỦY_VIÊN',
        hasConflictOfInterest: false,
      },
    ],
  },
  {
    id: 'council-02',
    code: 'HD-NT-2026-01',
    name: 'Hội đồng Đánh giá Nghiệm thu Đề tài Cấp cơ sở Năm 2026 (Chuyên ngành Can thiệp & Ngoại)',
    type: 'ACCEPTANCE',
    projectIds: ['proj-08'],
    projectAssignments: [
      {
        projectId: 'proj-08',
        reviewerAssignments: [
          { reviewerId: 'user-05', reviewerName: 'PGS.TS.BS. Phạm Đức Dũng', reviewerOrder: 1 },
          { reviewerId: 'user-06', reviewerName: 'TS.BS. Hoàng Minh Tuấn', reviewerOrder: 2 }
        ],
        notes: 'Kiểm tra hồ sơ bệnh án và số liệu phẫu thuật',
      },
    ],
    minMembers: 3,
    requiredReviewerCount: 2,
    meetingDate: '2026-02-10T14:00:00+07:00',
    location: 'Hội trường Bệnh viện',
    minPassRatio: 0.6,
    status: 'ESTABLISHED',
    members: [
      {
        id: 'cm-06',
        councilId: 'council-02',
        userId: 'user-05',
        userFullName: 'PGS.TS.BS. Phạm Đức Dũng',
        academicTitle: 'PGS.TS.BS',
        departmentName: 'Khoa Tim mạch Can thiệp',
        roleInCouncil: 'CHỦ_TỊCH',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-07',
        councilId: 'council-02',
        userId: 'user-07',
        userFullName: 'BS.CKI. Đỗ Bích Ngọc',
        academicTitle: 'BS.CKI',
        departmentName: 'Phòng Quản lý NCKH',
        roleInCouncil: 'THƯ_KÝ',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-07b',
        councilId: 'council-02',
        userId: 'user-06',
        userFullName: 'TS.BS. Hoàng Minh Tuấn',
        academicTitle: 'TS.BS',
        departmentName: 'Khoa Hồi sức tích cực',
        roleInCouncil: 'PHẢN_BIỆN',
        hasConflictOfInterest: false,
      }
    ],
  },
  {
    id: 'council-03',
    code: 'HD-NT-2024-01',
    name: 'Hội đồng Đánh giá Nghiệm thu Đề tài Cấp cơ sở Năm 2024 (Khối Nội khoa)',
    type: 'ACCEPTANCE',
    projectIds: ['proj-09'],
    projectAssignments: [
      {
        projectId: 'proj-09',
        reviewerAssignments: [
          { reviewerId: 'user-05', reviewerName: 'PGS.TS.BS. Phạm Đức Dũng', reviewerOrder: 1 },
          { reviewerId: 'user-06', reviewerName: 'TS.BS. Hoàng Minh Tuấn', reviewerOrder: 2 }
        ],
        notes: 'Kiểm tra hồ sơ bệnh án và số liệu thu thập',
      },
    ],
    minMembers: 3,
    requiredReviewerCount: 2,
    meetingDate: '2024-12-25T14:00:00+07:00',
    location: 'Hội trường Bệnh viện',
    minPassRatio: 0.6,
    status: 'CONCLUDED',
    members: [
      {
        id: 'cm-08',
        councilId: 'council-03',
        userId: 'user-05',
        userFullName: 'PGS.TS.BS. Phạm Đức Dũng',
        academicTitle: 'PGS.TS.BS',
        departmentName: 'Khoa Tim mạch Can thiệp',
        roleInCouncil: 'CHỦ_TỊCH',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-09',
        councilId: 'council-03',
        userId: 'user-07',
        userFullName: 'BS.CKI. Đỗ Bích Ngọc',
        academicTitle: 'BS.CKI',
        departmentName: 'Phòng Quản lý NCKH',
        roleInCouncil: 'THƯ_KÝ',
        hasConflictOfInterest: false,
      },
      {
        id: 'cm-09b',
        councilId: 'council-03',
        userId: 'user-06',
        userFullName: 'TS.BS. Hoàng Minh Tuấn',
        academicTitle: 'TS.BS',
        departmentName: 'Khoa Hồi sức tích cực',
        roleInCouncil: 'PHẢN_BIỆN',
        hasConflictOfInterest: false,
      }
    ],
    minutes: [
      {
        id: 'minutes-c03-p09',
        councilId: 'council-03',
        projectId: 'proj-09',
        meetingDate: '2024-12-25T14:00:00+07:00',
        location: 'Hội trường Bệnh viện',
        secretaryId: 'user-07',
        secretaryName: 'BS.CKI. Đỗ Bích Ngọc',
        chairId: 'user-05',
        chairName: 'PGS.TS.BS. Phạm Đức Dũng',
        attendeesCount: 3,
        summaryOpinions: 'Hội đồng thống nhất kết quả nghiên cứu đáp ứng yêu cầu nghiệm thu.',
        conclusion: 'APPROVED',
        averageScore: 86.7,
        passVoteCount: 3,
        totalVoteCount: 3,
        ratingLabel: 'Đạt',
        status: 'SIGNED',
        secretarySignedAt: '2024-12-25T16:00:00+07:00',
        chairSignedAt: '2024-12-25T16:10:00+07:00',
      },
    ],

  },
];