export type MedicalTemplateCategory =
  | 'PROPOSAL'
  | 'ETHICS'
  | 'COUNCIL'
  | 'PROGRESS_FINANCE'
  | 'ACCEPTANCE';

export type MedicalTemplateFormat = 'WORD' | 'EXCEL' | 'PDF';

export interface MedicalTemplate {
  id: string;
  code: string;
  name: string;
  description: string;
  category: MedicalTemplateCategory;
  categoryLabel: string;
  format: MedicalTemplateFormat;
  size: string;
  updatedAt: string;
  legalRef: string;
  templateVersion: string;
  downloadFileName: string;
  previewSummary: string[];
}

export const MEDICAL_TEMPLATES_DATA: MedicalTemplate[] = [
  // ── Nhóm 1: Hồ sơ Đăng ký & Thuyết minh (TT 09/2024/TT-BYT) ──
  {
    id: 'bm-01-nckh',
    code: 'BM-01/NCKH',
    name: 'Đơn đăng ký đề tài Nghiên cứu Khoa học Cấp cơ sở',
    description: 'Đơn đề nghị thực hiện nghiên cứu khoa học dành cho cán bộ y tế, bác sĩ chủ nhiệm đề tài gửi Phòng Quản lý NCKH và Hội đồng Khoa học.',
    category: 'PROPOSAL',
    categoryLabel: 'Đăng ký & Thuyết minh',
    format: 'WORD',
    size: '88 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư 09/2024/TT-BYT',
    templateVersion: 'v2.4',
    downloadFileName: 'BM-01-NCKH-Don-dang-ky-de-tai-cap-co-so.docx',
    previewSummary: [
      '1. Thông tin người nộp đơn (Họ tên, chức vụ, học hàm học vị, đơn vị)',
      '2. Tên đề tài, loại hình nghiên cứu (thử nghiệm lâm sàng / dịch tễ / ứng dụng kỹ thuật)',
      '3. Mục tiêu tổng quát và đối tượng người bệnh tham gia',
      '4. Dự kiến thời gian thực hiện và tổng kinh phí đề xuất',
      '5. Cam kết của Chủ nhiệm đề tài và Trưởng khoa/Phòng chủ quản',
    ],
  },
  {
    id: 'bm-02-nckh',
    code: 'BM-02/NCKH',
    name: 'Thuyết minh Đề tài Nghiên cứu Khoa học Y tế',
    description: 'Đề cương chi tiết theo cấu trúc chuẩn quốc gia: Tổng quan y văn, đối tượng & phương pháp nghiên cứu, đạo đức y sinh, kế hoạch triển khai và dự toán ngân sách.',
    category: 'PROPOSAL',
    categoryLabel: 'Đăng ký & Thuyết minh',
    format: 'WORD',
    size: '165 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư 09/2024/TT-BYT',
    templateVersion: 'v3.1',
    downloadFileName: 'BM-02-NCKH-Thuyet-minh-de-tai-NCKH-Y-te.docx',
    previewSummary: [
      'Phần 1: Thông tin chung (Mã số, tên đề tài, chủ nhiệm, các đơn vị phối hợp)',
      'Phần 2: Tính cấp thiết và tổng quan tình hình nghiên cứu trong & ngoài nước',
      'Phần 3: Mục tiêu nghiên cứu (Mục tiêu chung & mục tiêu cụ thể)',
      'Phần 4: Đối tượng và phương pháp nghiên cứu (Thiết kế, cỡ mẫu, tiêu chuẩn chọn/loại trừ, xử lý số liệu)',
      'Phần 5: Đạo đức trong nghiên cứu y sinh học',
      'Phần 6: Kế hoạch và tiến độ thực hiện chi tiết',
      'Phần 7: Dự toán kinh phí và hiệu quả ứng dụng điều trị',
    ],
  },
  {
    id: 'bm-03-nckh',
    code: 'BM-03/NCKH',
    name: 'Lý lịch Khoa học của Chủ nhiệm & Thành viên Nghiên cứu (CV)',
    description: 'Bản khai lý lịch khoa học cá nhân, quá trình đào tạo, kinh nghiệm chuyên môn và các công trình/bài báo y học đã công bố trong 5 năm gần nhất.',
    category: 'PROPOSAL',
    categoryLabel: 'Đăng ký & Thuyết minh',
    format: 'WORD',
    size: '95 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư 09/2024/TT-BYT',
    templateVersion: 'v2.0',
    downloadFileName: 'BM-03-NCKH-Ly-lich-khoa-hoc-chuyen-gia.docx',
    previewSummary: [
      '1. Thông tin lý lịch trích ngang, chứng chỉ hành nghề y',
      '2. Quá trình đào tạo đại học, sau đại học (ThS, BS.CKII, TS)',
      '3. Quá trình công tác lâm sàng và giảng dạy',
      '4. Các đề tài NCKH các cấp đã chủ nhiệm hoặc tham gia',
      '5. Danh mục các công trình bài báo đã đăng trên tạp chí Y học / Scopus / ISI',
    ],
  },
  {
    id: 'bm-04-nckh',
    code: 'BM-04/NCKH',
    name: 'Bảng Dự toán Kinh phí Chi tiết Đề tài NCKH',
    description: 'Bảng tính tự động theo định mức viện phí và chế độ công tác phí NCKH: Công lao động khoa học, hóa chất vật tư y tế tiêu hao, hội thảo khoa học và thẩm định.',
    category: 'PROPOSAL',
    categoryLabel: 'Đăng ký & Thuyết minh',
    format: 'EXCEL',
    size: '210 KB',
    updatedAt: '10/01/2026',
    legalRef: 'Quy chế Tài chính Bệnh viện',
    templateVersion: 'v2.5',
    downloadFileName: 'BM-04-NCKH-Du-toan-kinh-phi-chi-tiet.xlsx',
    previewSummary: [
      'Sheet 1: Tổng hợp kinh phí các nguồn (Ngân sách BV, Quỹ phát triển sự nghiệp, Nguồn khác)',
      'Sheet 2: Chi thù lao cho các thành viên nghiên cứu và chuyên gia phản biện',
      'Sheet 3: Chi mua sắm sinh phẩm, kit test, hóa chất và vật tư tiêu hao',
      'Sheet 4: Chi thu thập bệnh án và phân tích xét nghiệm cận lâm sàng',
      'Sheet 5: Chi hội thảo khoa học, in ấn kỷ yếu và nghiệm thu',
    ],
  },

  // ── Nhóm 2: Đạo đức Y sinh - IRB Approval (TT 43/2024/TT-BYT) ──
  {
    id: 'bm-01-irb',
    code: 'BM-01/IRB',
    name: 'Đơn đề nghị Đánh giá Đạo đức trong Nghiên cứu Y sinh học',
    description: 'Hồ sơ gửi Hội đồng Đạo đức trong Nghiên cứu Y sinh học (IRB) cấp cơ sở để xin cấp phép phê duyệt đạo đức trước khi tuyển chọn người bệnh.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'WORD',
    size: '104 KB',
    updatedAt: '15/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT',
    templateVersion: 'v4.0',
    downloadFileName: 'BM-01-IRB-Don-de-nghi-danh-gia-dao-duc-y-sinh.docx',
    previewSummary: [
      '1. Tên nghiên cứu và phân loại mức độ rủi ro đối với người tham gia',
      '2. Đánh giá tỷ lệ lợi ích / nguy cơ đối với người bệnh',
      '3. Biện pháp bảo mật thông tin và quyền riêng tư của hồ sơ bệnh án',
      '4. Quy trình xử trí biến cố bất lợi (AE/SAE) trong quá trình nghiên cứu',
      '5. Kế hoạch bồi thường hoặc hỗ trợ y tế nếu phát sinh rủi ro',
    ],
  },
  {
    id: 'bm-02-irb',
    code: 'BM-02/IRB',
    name: 'Mẫu Phiếu Cung cấp Thông tin & Đồng ý Tham gia Nghiên cứu (ICF)',
    description: 'Mẫu Informed Consent Form (ICF) chuẩn ngôn ngữ dễ hiểu dành cho người bệnh hoặc người đại diện hợp pháp ký xác nhận trước khi tham gia.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'WORD',
    size: '118 KB',
    updatedAt: '15/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT',
    templateVersion: 'v3.2',
    downloadFileName: 'BM-02-IRB-Phieu-dong-y-tham-gia-nghien-cuu-ICF.docx',
    previewSummary: [
      'Phần I: Bản cung cấp thông tin (Mục đích, thời gian, can thiệp y khoa, quyền rút lui tự nguyện)',
      'Phần II: Quyền lợi người bệnh (Khám xét nghiệm miễn phí, hỗ trợ đi lại nếu có)',
      'Phần III: Rủi ro có thể gặp và số điện thoại đường dây nóng hỗ trợ 24/7',
      'Phần IV: Bản cam kết đồng thuận và chữ ký của Người bệnh / Thân nhân / Bác sĩ tư vấn',
    ],
  },
  {
    id: 'bm-03-irb',
    code: 'BM-03/IRB',
    name: 'Bệnh án Nghiên cứu / Phiếu Thu thập Dữ liệu Lâm sàng (CRF)',
    description: 'Case Report Form (CRF) chuẩn hóa các trường thông tin lâm sàng, cận lâm sàng, tiền sử, phác đồ điều trị và các chỉ số theo dõi sau can thiệp.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'WORD',
    size: '130 KB',
    updatedAt: '15/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM-03-IRB-Benh-an-nghien-cuu-CRF.docx',
    previewSummary: [
      '1. Mã số định danh bệnh nhân (Anonymized Patient ID), tuổi, giới, nghề nghiệp',
      '2. Bệnh sử, triệu chứng lâm sàng và chẩn đoán ICD-10',
      '3. Kết quả xét nghiệm máu, sinh hóa, chẩn đoán hình ảnh (X-quang, CT, MRI)',
      '4. Liều lượng thuốc, kỹ thuật can thiệp và đáp ứng điều trị',
      '5. Đánh giá biến chứng và thời điểm xuất viện',
    ],
  },
  {
    id: 'bm-04-irb',
    code: 'BM-04/IRB',
    name: 'Giấy Chứng nhận Chấp thuận Đạo đức Y sinh (IRB Approval Certificate)',
    description: 'Chứng thư chính thức của Hội đồng Đạo đức Bệnh viện xác nhận đề cương đáp ứng đầy đủ nguyên tắc Tuyên ngôn Helsinki và Thông tư 43/2024/TT-BYT.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'PDF',
    size: '280 KB',
    updatedAt: '20/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT',
    templateVersion: 'v1.0',
    downloadFileName: 'BM-04-IRB-Giay-chung-nhan-chap-thuan-dao-duc-IRB.pdf',
    previewSummary: [
      '1. Quyết định số và ngày họp thông qua của Hội đồng Đạo đức',
      '2. Thông tin đề tài và Chủ nhiệm đề tài được cấp phép',
      '3. Thời hạn hiệu lực của giấy chứng nhận (12 tháng - 24 tháng)',
      '4. Các điều kiện đi kèm (báo cáo biến cố SAE trong 24h)',
      '5. Chữ ký Chủ tịch Hội đồng và Dấu pháp nhân Bệnh viện',
    ],
  },

  // ── Nhóm 3: Hội đồng & Thẩm định ──
  {
    id: 'bm-01-hd',
    code: 'BM-01/HĐ',
    name: 'Phiếu Nhận xét & Đánh giá Đề cương NCKH (Dành cho Phản biện)',
    description: 'Phiếu chấm điểm thẩm định đề cương chi tiết dành cho Chuyên gia phản biện 1, Phản biện 2 và các Ủy viên Hội đồng Khoa học.',
    category: 'COUNCIL',
    categoryLabel: 'Hội đồng & Thẩm định',
    format: 'PDF',
    size: '190 KB',
    updatedAt: '05/02/2026',
    legalRef: 'Quy trình ISO Quản lý NCKH',
    templateVersion: 'v2.2',
    downloadFileName: 'BM-01-HD-Phieu-danh-gia-de-cuong-phan-bien.pdf',
    previewSummary: [
      'Tiêu chí 1: Tính cấp thiết và giá trị thực tiễn đối với công tác khám chữa bệnh (Tối đa 20 điểm)',
      'Tiêu chí 2: Mục tiêu và nội dung nghiên cứu (Tối đa 25 điểm)',
      'Tiêu chí 3: Phương pháp nghiên cứu và tính khả thi (Tối đa 30 điểm)',
      'Tiêu chí 4: Năng lực nghiên cứu và cơ sở vật chất (Tối đa 15 điểm)',
      'Tiêu chí 5: Dự toán kinh phí hợp lý (Tối đa 10 điểm)',
      'Kết luận: Đạt / Yêu cầu chỉnh sửa bổ sung / Không đạt',
    ],
  },
  {
    id: 'bm-02-hd',
    code: 'BM-02/HĐ',
    name: 'Biên bản Họp Hội đồng Khoa học Xét duyệt Đề cương',
    description: 'Mẫu biên bản ghi nhận toàn bộ diễn biến phiên họp Hội đồng: Trình bày của Chủ nhiệm, ý kiến nhận xét của phản biện, bỏ phiếu và kết luận của Chủ tịch Hội đồng.',
    category: 'COUNCIL',
    categoryLabel: 'Hội đồng & Thẩm định',
    format: 'WORD',
    size: '115 KB',
    updatedAt: '05/02/2026',
    legalRef: 'Thông tư 09/2024/TT-BYT',
    templateVersion: 'v2.0',
    downloadFileName: 'BM-02-HD-Bien-ban-hop-hoi-dong-xet-duyet-de-cuong.docx',
    previewSummary: [
      '1. Thành phần Hội đồng có mặt (Chủ tịch, Thư ký, 2 Phản biện, các Ủy viên)',
      '2. Tóm tắt nội dung báo cáo của Chủ nhiệm đề tài',
      '3. Ý kiến đánh giá của Chuyên gia Phản biện 1 và Phản biện 2',
      '4. Tổng hợp kết quả chấm điểm và kết quả bỏ phiếu kín',
      '5. Kết luận chính thức và danh mục nội dung yêu cầu bổ sung/sửa đổi',
    ],
  },
  {
    id: 'bm-03-hd',
    code: 'BM-03/HĐ',
    name: 'Phiếu Đánh giá Nghiệm thu Đề tài NCKH Cấp cơ sở',
    description: 'Phiếu chấm điểm nghiệm thu kết quả nghiên cứu hoàn chỉnh, đánh giá sản phẩm khoa học, bài báo công bố và hiệu quả ứng dụng lâm sàng.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'PDF',
    size: '220 KB',
    updatedAt: '12/02/2026',
    legalRef: 'Thông tư 09/2024/TT-BYT',
    templateVersion: 'v3.0',
    downloadFileName: 'BM-03-HD-Phieu-danh-gia-nghiem-thu-de-tai.pdf',
    previewSummary: [
      'Tiêu chí 1: Mức độ hoàn thành so với đề cương đã được phê duyệt (Tối đa 30 điểm)',
      'Tiêu chí 2: Chất lượng Báo cáo tổng kết và độ tin cậy của số liệu (Tối đa 30 điểm)',
      'Tiêu chí 3: Giá trị khoa học và ứng dụng thực tiễn trong bệnh viện (Tối đa 25 điểm)',
      'Tiêu chí 4: Sản phẩm khoa học (Quy trình kỹ thuật / Bài báo công bố) (Tối đa 15 điểm)',
      'Xếp loại: Xuất sắc (>=90đ) / Đạt (70-89đ) / Không đạt (<70đ)',
    ],
  },

  // ── Nhóm 4: Tiến độ & Tài chính Quyết toán ──
  {
    id: 'bm-01-bctd',
    code: 'BM-01/BCTĐ',
    name: 'Báo cáo Tiến độ Thực hiện Đề tài Định kỳ (6 Tháng / 1 Năm)',
    description: 'Báo cáo giám sát tiến độ thực hiện các mốc nghiên cứu, số lượng bệnh nhân đã thu thập, khó khăn vướng mắc và kế hoạch giai đoạn tiếp theo.',
    category: 'PROGRESS_FINANCE',
    categoryLabel: 'Tiến độ & Tài chính',
    format: 'WORD',
    size: '92 KB',
    updatedAt: '18/01/2026',
    legalRef: 'Thông tư 09/2024/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM-01-BCTD-Bao-cao-tien-do-dinh-ky.docx',
    previewSummary: [
      '1. Thông tin chung về đề tài và thời gian báo cáo',
      '2. Khối lượng công việc đã hoàn thành so với kế hoạch đề cương',
      '3. Số lượng mẫu / bệnh án đã thu thập và phân tích',
      '4. Tình hình giải ngân kinh phí giai đoạn báo cáo',
      '5. Đề xuất, kiến nghị điều chỉnh nếu có khó khăn phát sinh',
    ],
  },
  {
    id: 'bm-01-dc',
    code: 'BM-01/ĐC',
    name: 'Đơn xin Điều chỉnh Đề tài (Gia hạn / Đổi Chủ nhiệm / Kinh phí)',
    description: 'Đơn xin điều chỉnh nội dung hợp đồng nghiên cứu: Gia hạn thời gian nghiên cứu, thay đổi nhân sự chủ nhiệm/đồng nghiên cứu hoặc điều chuyển dự toán.',
    category: 'PROGRESS_FINANCE',
    categoryLabel: 'Tiến độ & Tài chính',
    format: 'WORD',
    size: '86 KB',
    updatedAt: '22/01/2026',
    legalRef: 'Quy chế Quản lý NCKH Bệnh viện',
    templateVersion: 'v1.8',
    downloadFileName: 'BM-01-DC-Don-xin-dieu-chinh-de-tai.docx',
    previewSummary: [
      '1. Loại đề nghị điều chỉnh: Gia hạn / Thay đổi nhân sự / Điều chuyển kinh phí / Thay đổi cỡ mẫu',
      '2. Lý do chi tiết và khách quan của đề nghị điều chỉnh',
      '3. Kế hoạch hoàn thành sau khi được điều chỉnh',
      '4. Ý kiến của Trưởng đơn vị công tác và Chuyên viên phụ trách',
      '5. Phê duyệt của Ban Giám đốc Bệnh viện',
    ],
  },
  {
    id: 'bm-01-qt',
    code: 'BM-01/QT',
    name: 'Giấy Đề nghị Thanh toán & Quyết toán Kinh phí NCKH',
    description: 'Bảng tổng hợp chứng từ tài chính, hóa đơn, bảng kê chi thù lao và biên nhận để làm thủ tục thanh quyết toán kinh phí tại Phòng Tài chính - Kế toán.',
    category: 'PROGRESS_FINANCE',
    categoryLabel: 'Tiến độ & Tài chính',
    format: 'EXCEL',
    size: '185 KB',
    updatedAt: '25/01/2026',
    legalRef: 'Quy chế Tài chính Bệnh viện',
    templateVersion: 'v2.3',
    downloadFileName: 'BM-01-QT-Giay-de-nghi-thanh-toan-quyet-toan-kinh-phi.xlsx',
    previewSummary: [
      'Sheet 1: Bảng tổng hợp quyết toán các mục chi theo đúng hợp đồng phê duyệt',
      'Sheet 2: Bảng kê chứng từ thanh toán (Hóa đơn GTGT, phiếu xuất kho, phiếu chi)',
      'Sheet 3: Danh sách ký nhận thù lao nghiên cứu khoa học có khấu trừ thuế TNCN',
      'Sheet 4: Bảng đối chiếu số dư tạm ứng và số tiền đề nghị thanh toán bổ sung/hoàn ứng',
    ],
  },
];
