export type MedicalTemplateCategory =
  | 'PROPOSAL'
  | 'ETHICS'
  | 'COUNCIL'
  | 'PROGRESS_FINANCE'
  | 'ACCEPTANCE';

export type MedicalTemplateFormat = 'WORD' | 'EXCEL' | 'PDF';

export interface MedicalTemplate {
  id: string;
  code: string;
  name: string;
  description: string;
  category: MedicalTemplateCategory;
  categoryLabel: string;
  format: MedicalTemplateFormat;
  size: string;
  updatedAt: string;
  legalRef: string;
  templateVersion: string;
  downloadFileName: string;
  previewSummary: string[];
}

export const MEDICAL_TEMPLATES_DATA: MedicalTemplate[] = [
  // ── Nhóm 1: Hồ sơ Đăng ký & Thuyết minh (Chuẩn ISO & Thông tư Y tế/KH&CN) ──
  {
    id: 'bm-01-nckh',
    code: 'BM1/QTQL.NC2.1.1',
    name: 'Phiếu đề xuất đề tài nghiên cứu khoa học cấp cơ sở',
    description: 'Phiếu đăng ký sơ bộ ý tưởng nghiên cứu, xác định tính cấp thiết, mục tiêu và dự toán khái quát gửi Phòng NCKH.',
    category: 'PROPOSAL',
    categoryLabel: 'Đăng ký & Thuyết minh',
    format: 'WORD',
    size: '45 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 03/2017/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM1_QTQL.NC2.1.1_Phieu_de_xuat_de_tai_co_so.docx',
    previewSummary: [
      '1. Tên đề tài đề xuất',
      '2. Sự cần thiết của đề tài',
      '3. Mục tiêu & nội dung chính',
      '4. Sản phẩm dự kiến đạt được',
      '5. Khả năng ứng dụng & kinh phí dự kiến',
    ],
  },
  {
    id: 'bm-02-nckh',
    code: 'BM2/QTQL.NC2.1.1',
    name: 'Mẫu thuyết minh đề cương đề tài',
    description: 'Đề cương khoa học chi tiết gồm tổng quan y văn, đối tượng và phương pháp nghiên cứu, tiến độ chi tiết và thuyết minh tài chính.',
    category: 'PROPOSAL',
    categoryLabel: 'Đăng ký & Thuyết minh',
    format: 'WORD',
    size: '120 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 37/2010/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM2_QTQL.NC2.1.1_Thuyet_minh_de_cuong_de_tai.docx',
    previewSummary: [
      '1. Thông tin chung về đề tài',
      '2. Tổng quan tình hình nghiên cứu',
      '3. Đối tượng và phương pháp nghiên cứu',
      '4. Tiến độ và nội dung thực hiện chi tiết',
      '5. Dự toán kinh phí phân mục chi',
    ],
  },
  {
    id: 'bm-07-nckh',
    code: 'BM7/QTQL.NC2.1.1',
    name: 'Mẫu Biên bản giải trình chỉnh sửa thuyết minh',
    description: 'Bảng đối chiếu, giải trình việc tiếp thu chỉnh sửa đề cương theo ý kiến đóng góp của Hội đồng xét duyệt.',
    category: 'PROPOSAL',
    categoryLabel: 'Đăng ký & Thuyết minh',
    format: 'WORD',
    size: '42 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 37/2010/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM7_QTQL.NC2.1.1_Bien_ban_giai_trinh_chinh_sua_thuyet_minh.docx',
    previewSummary: [
      '1. Bảng đối chiếu ý kiến Hội đồng và nội dung đã tiếp thu',
      '2. Trang số/Vị trí chỉnh sửa trong đề cương v2.0',
      '3. Giải trình các điểm bảo lưu ý kiến (nếu có)',
      '4. Xác nhận của Thư ký và Chủ tịch Hội đồng',
    ],
  },

  // ── Nhóm 2: Đạo đức Y sinh - IRB Approval (Thông tư 43/2024/TT-BYT) ──
  {
    id: 'bm-01-irb',
    code: 'BM-01/IRB',
    name: 'Đơn đề nghị Đánh giá Đạo đức trong Nghiên cứu Y sinh học',
    description: 'Hồ sơ gửi Hội đồng Đạo đức trong Nghiên cứu Y sinh học (IRB) cấp cơ sở để xin cấp phép phê duyệt đạo đức trước khi tuyển chọn người bệnh.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'WORD',
    size: '104 KB',
    updatedAt: '15/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT (IRB)',
    templateVersion: 'v4.0',
    downloadFileName: 'BM-01-IRB-Don-de-nghi-danh-gia-dao-duc-y-sinh.docx',
    previewSummary: [
      '1. Tên nghiên cứu và phân loại mức độ rủi ro đối với người tham gia',
      '2. Đánh giá tỷ lệ lợi ích / nguy cơ đối với người bệnh',
      '3. Biện pháp bảo mật thông tin và quyền riêng tư của hồ sơ bệnh án',
      '4. Quy trình xử trí biến cố bất lợi (AE/SAE) trong quá trình nghiên cứu',
      '5. Kế hoạch bồi thường hoặc hỗ trợ y tế nếu phát sinh rủi ro',
    ],
  },
  {
    id: 'bm-02-irb',
    code: 'BM-02/IRB',
    name: 'Mẫu Phiếu Cung cấp Thông tin & Đồng ý Tham gia Nghiên cứu (ICF)',
    description: 'Mẫu Informed Consent Form (ICF) dành cho người bệnh hoặc thân nhân ký xác nhận trước khi tham gia nghiên cứu y sinh học.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'WORD',
    size: '118 KB',
    updatedAt: '15/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT (IRB)',
    templateVersion: 'v3.2',
    downloadFileName: 'BM-02-IRB-Phieu-dong-y-tham-gia-nghien-cuu-ICF.docx',
    previewSummary: [
      'Phần I: Bản cung cấp thông tin (Mục đích, thời gian, can thiệp y khoa, quyền rút lui tự nguyện)',
      'Phần II: Quyền lợi người bệnh (Khám xét nghiệm miễn phí, hỗ trợ đi lại nếu có)',
      'Phần III: Rủi ro có thể gặp và số điện thoại đường dây nóng hỗ trợ 24/7',
      'Phần IV: Bản cam kết đồng thuận và chữ ký của Người bệnh / Thân nhân / Bác sĩ tư vấn',
    ],
  },
  {
    id: 'bm-03-irb',
    code: 'BM-03/IRB',
    name: 'Bệnh án Nghiên cứu / Phiếu Thu thập Dữ liệu Lâm sàng (CRF)',
    description: 'Case Report Form (CRF) thu thập số liệu lâm sàng, tiền sử, phác đồ điều trị phục vụ phân tích dữ liệu y tế.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'WORD',
    size: '130 KB',
    updatedAt: '15/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT (IRB)',
    templateVersion: 'v2.1',
    downloadFileName: 'BM-03-IRB-Benh-an-nghien-cuu-CRF.docx',
    previewSummary: [
      '1. Mã số định danh bệnh nhân (Anonymized Patient ID), tuổi, giới, nghề nghiệp',
      '2. Bệnh sử, triệu chứng lâm sàng và chẩn đoán ICD-10',
      '3. Kết quả xét nghiệm máu, sinh hóa, chẩn đoán hình ảnh (X-quang, CT, MRI)',
      '4. Liều lượng thuốc, kỹ thuật can thiệp và đáp ứng điều trị',
      '5. Đánh giá biến chứng và thời điểm xuất viện',
    ],
  },
  {
    id: 'bm-04-irb',
    code: 'BM-04/IRB',
    name: 'Giấy Chứng nhận Chấp thuận Đạo đức Y sinh (IRB Certificate)',
    description: 'Quyết định cấp chứng nhận IRB chính thức của Hội đồng Đạo đức Bệnh viện cho phép triển khai nghiên cứu.',
    category: 'ETHICS',
    categoryLabel: 'Đạo đức Y sinh (IRB)',
    format: 'PDF',
    size: '280 KB',
    updatedAt: '20/01/2026',
    legalRef: 'Thông tư 43/2024/TT-BYT (IRB)',
    templateVersion: 'v1.0',
    downloadFileName: 'BM-04-IRB-Giay-chung-nhan-chap-thuan-dao-duc-IRB.pdf',
    previewSummary: [
      '1. Quyết định số và ngày họp thông qua của Hội đồng Đạo đức',
      '2. Thông tin đề tài và Chủ nhiệm đề tài được cấp phép',
      '3. Thời hạn hiệu lực của giấy chứng nhận (12 tháng - 24 tháng)',
      '4. Các điều kiện đi kèm (báo cáo biến cố SAE trong 24h)',
      '5. Chữ ký Chủ tịch Hội đồng và Dấu pháp nhân Bệnh viện',
    ],
  },

  // ── Nhóm 3: Hội đồng & Thẩm định (Thông tư 37/2010/TT-BYT) ──
  {
    id: 'bm-03-nckh',
    code: 'BM3/QTQL.NC2.1.1',
    name: 'Mẫu tờ trình về việc thành lập Hội đồng xét duyệt thuyết minh',
    description: 'Tờ trình ban lãnh đạo bệnh viện về việc đề nghị phê duyệt danh sách thành viên Hội đồng khoa học xét duyệt thuyết minh đề cương.',
    category: 'COUNCIL',
    categoryLabel: 'Hội đồng & Thẩm định',
    format: 'WORD',
    size: '38 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 37/2010/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM3_QTQL.NC2.1.1_To_trinh_thanh_lap_Hoi_dong_xet_duyet.docx',
    previewSummary: [
      '1. Căn cứ pháp lý thành lập hội đồng',
      '2. Đề xuất danh sách thành viên (Chủ tịch, Phản biện, Thư ký, Ủy viên)',
      '3. Thời gian và địa điểm dự kiến họp',
      '4. Ý kiến của Phòng Quản lý NCKH',
    ],
  },
  {
    id: 'bm-04-nckh',
    code: 'BM4/QTQL.NC2.1.1',
    name: 'Mẫu phiếu nhận xét thuyết minh',
    description: 'Bản nhận xét khoa học chi tiết của Chuyên gia phản biện về đề cương thuyết minh đề tài.',
    category: 'COUNCIL',
    categoryLabel: 'Hội đồng & Thẩm định',
    format: 'WORD',
    size: '52 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 37/2010/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM4_QTQL.NC2.1.1_Phieu_nhan_xet_thuyet_minh.docx',
    previewSummary: [
      '1. Ý kiến về tính cấp thiết & tính mới',
      '2. Nhận xét về phương pháp nghiên cứu',
      '3. Đánh giá tính khả thi & nhân lực thực hiện',
      '4. Nhận xét về kinh phí đề xuất',
      '5. Các điểm cần sửa đổi, bổ sung',
    ],
  },
  {
    id: 'bm-05-nckh',
    code: 'BM5/QTQL.NC2.1.1',
    name: 'Mẫu Phiếu đánh giá thuyết minh',
    description: 'Phiếu chấm điểm cụ thể theo thang 100 dành cho thành viên Hội đồng đánh giá thuyết minh đề cương.',
    category: 'COUNCIL',
    categoryLabel: 'Hội đồng & Thẩm định',
    format: 'WORD',
    size: '48 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 37/2010/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM5_QTQL.NC2.1.1_Phieu_danh_gia_thuyet_minh.docx',
    previewSummary: [
      '1. Điểm số cho tính cấp thiết (tối đa 20đ)',
      '2. Điểm số cho phương pháp nghiên cứu (tối đa 30đ)',
      '3. Điểm số cho tính khả thi (tối đa 20đ)',
      '4. Điểm số cho giá trị ứng dụng (tối đa 20đ)',
      '5. Điểm số cho dự toán kinh phí (tối đa 10đ)',
    ],
  },
  {
    id: 'bm-06-nckh',
    code: 'BM6/QTQL.NC2.1.1',
    name: 'Mẫu Biên bản họp đánh giá thuyết minh',
    description: 'Biên bản chính thức kết quả họp Hội đồng Khoa học xét duyệt thuyết minh đề cương đề tài.',
    category: 'COUNCIL',
    categoryLabel: 'Hội đồng & Thẩm định',
    format: 'WORD',
    size: '75 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 37/2010/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM6_QTQL.NC2.1.1_Bien_ban_hop_danh_gia_thuyet_minh.docx',
    previewSummary: [
      '1. Thành phần Hội đồng tham dự',
      '2. Điểm số trung bình & Xếp loại kết quả',
      '3. Tổng hợp ý kiến nhận xét của các ủy viên',
      '4. Kết luận của Chủ tịch Hội đồng về kinh phí và phương án thông qua',
    ],
  },
  {
    id: 'bm-08-nckh',
    code: 'BM8/QTQL.NC2.1.1',
    name: 'Mẫu tờ trình về việc ra Quyết định phê duyệt đề tài',
    description: 'Tờ trình đề nghị ban hành Quyết định phê duyệt chính thức giao thực hiện đề tài sau khi chốt thuyết minh.',
    category: 'COUNCIL',
    categoryLabel: 'Hội đồng & Thẩm định',
    format: 'WORD',
    size: '36 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 37/2010/TT-BYT',
    templateVersion: 'v2.1',
    downloadFileName: 'BM8_QTQL.NC2.1.1_To_trinh_ra_Quyet_dinh_phe_duyet.docx',
    previewSummary: [
      '1. Căn cứ kết quả họp Hội đồng khoa học đạt yêu cầu',
      '2. Đề nghị ban hành mã số đề tài chính thức',
      '3. Đề nghị phê duyệt kinh phí và nguồn cấp vốn',
      '4. Dự thảo Quyết định giao nhiệm vụ đính kèm',
    ],
  },

  // ── Nhóm 4: Kiểm tra & Điều chỉnh (Thông tư 04/2015/TT-BKHCN) ──
  {
    id: 'bm-09-nckh',
    code: 'BM9/QTQL.NC2.1.1',
    name: 'Mẫu Báo cáo định kỳ',
    description: 'Báo cáo định kỳ tình hình triển khai công việc, số liệu bệnh án thu thập và giải ngân theo tiến độ.',
    category: 'PROGRESS_FINANCE',
    categoryLabel: 'Tiến độ & Tài chính',
    format: 'WORD',
    size: '64 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 04/2015/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM9_QTQL.NC2.1.1_Bao_cao_dinh_ky_tien_do.docx',
    previewSummary: [
      '1. Tiến độ hoàn thành các mốc nghiên cứu',
      '2. Số lượng mẫu bệnh án đã thu thập được',
      '3. Khó khăn, vướng mắc phát sinh khi triển khai lâm sàng',
      '4. Kế hoạch chi tiết của giai đoạn tiếp theo',
    ],
  },
  {
    id: 'bm-10-nckh',
    code: 'BM10/QTQL.NC2.1.1',
    name: 'Mẫu Đơn xin gia hạn',
    description: 'Đơn đề nghị xin gia hạn thêm thời hạn thực hiện đề tài do các nguyên nhân khách quan trong lâm sàng.',
    category: 'PROGRESS_FINANCE',
    categoryLabel: 'Tiến độ & Tài chính',
    format: 'WORD',
    size: '40 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 04/2015/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM10_QTQL.NC2.1.1_Don_xin_gia_han_de_tai.docx',
    previewSummary: [
      '1. Thời gian đã thực hiện & Thời gian xin gia hạn đề xuất',
      '2. Lý do chi tiết (khách quan/chủ quan) cần gia hạn',
      '3. Tiến độ thực tế đã đạt được tại thời điểm nộp đơn',
      '4. Cam kết hoàn thành đúng hạn gia hạn',
    ],
  },

  // ── Nhóm 5: Đánh giá & Nghiệm thu (Thông tư 11/2014/TT-BKHCN & Thông tư 14/2014/TT-BKHCN) ──
  {
    id: 'bm-11-nckh',
    code: 'BM11/QTQL.NC2.1.1',
    name: 'Mẫu Báo cáo kết quả nghiệm thu',
    description: 'Báo cáo tổng kết toàn diện kết quả đề tài nghiên cứu lâm sàng để nộp Hội đồng nghiệm thu bệnh viện.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'WORD',
    size: '155 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 11/2014/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM11_QTQL.NC2.1.1_Bao_cao_ket_qua_nghiem_thu.docx',
    previewSummary: [
      '1. Tóm tắt kết quả nghiên cứu y văn & lâm sàng',
      '2. Số liệu thu thập và kết quả xử lý thống kê',
      '3. Đối chiếu sản phẩm thực tế với cam kết hợp đồng',
      '4. Kết luận khoa học & kiến nghị chuyển giao ứng dụng',
    ],
  },
  {
    id: 'bm-12-nckh',
    code: 'BM12/QTQL.NC2.1.1',
    name: 'Mẫu tờ trình về việc thành lập Hội đồng nghiệm thu đề tài',
    description: 'Tờ trình đề nghị thành lập Hội đồng nghiệm thu chính thức chấm điểm báo cáo kết quả đề tài.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'WORD',
    size: '39 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 11/2014/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM12_QTQL.NC2.1.1_To_trinh_thanh_lap_Hoi_dong_nghiem_thu.docx',
    previewSummary: [
      '1. Căn cứ hồ sơ nghiệm thu hợp lệ của chủ nhiệm',
      '2. Cơ cấu Hội đồng nghiệm thu đề xuất',
      '3. Thời gian và địa điểm tổ chức họp nghiệm thu',
      '4. Dự thảo Quyết định trình Giám đốc ký',
    ],
  },
  {
    id: 'bm-13-nckh',
    code: 'BM13/QTQL.NC2.1.1',
    name: 'Mẫu nhận xét nghiệm thu đề tài',
    description: 'Phiếu nhận xét kết quả thực tế đề tài của chuyên gia phản biện tại buổi nghiệm thu.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'WORD',
    size: '55 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 11/2014/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM13_QTQL.NC2.1.1_Phieu_nhan_xet_nghiem_thu.docx',
    previewSummary: [
      '1. Đánh giá tính trung thực và độ tin cậy của số liệu',
      '2. Nhận xét về chất lượng khoa học của báo cáo',
      '3. Đánh giá mức độ hoàn thành mục tiêu nghiên cứu',
      '4. Nhận xét về giá trị ứng dụng lâm sàng và công bố bài báo',
    ],
  },
  {
    id: 'bm-14-nckh',
    code: 'BM14/QTQL.NC2.1.1',
    name: 'Mẫu Đánh giá nghiệm thu đề tài',
    description: 'Phiếu chấm điểm nghiệm thu chi tiết từng tiêu chí khoa học, sản phẩm nghiên cứu của ủy viên hội đồng.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'WORD',
    size: '48 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 11/2014/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM14_QTQL.NC2.1.1_Phieu_danh_gia_nghiem_thu.docx',
    previewSummary: [
      '1. Điểm chất lượng khoa học (tối đa 30đ)',
      '2. Điểm mức độ hoàn thành so với cam kết (tối đa 30đ)',
      '3. Điểm giá trị ứng dụng lâm sàng thực tiễn (tối đa 25đ)',
      '4. Điểm sản phẩm đầu ra (bài báo, quy trình) (tối đa 15đ)',
    ],
  },
  {
    id: 'bm-15-nckh',
    code: 'BM15/QTQL.NC2.1.1',
    name: 'Mẫu Biên bản đánh giá nghiệm thu',
    description: 'Biên bản ghi nhận điểm số trung bình và xếp loại khoa học chính thức của Hội đồng nghiệm thu đề tài.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'WORD',
    size: '78 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 11/2014/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM15_QTQL.NC2.1.1_Bien_ban_danh_gia_nghiem_thu.docx',
    previewSummary: [
      '1. Thành phần Hội đồng tham gia nghiệm thu',
      '2. Điểm số trung bình cộng & Xếp loại (Xuất sắc/Đạt/Không đạt)',
      '3. Kết luận chi tiết của Chủ tịch Hội đồng nghiệm thu',
      '4. Chữ ký xác nhận của Thư ký và Chủ tịch Hội đồng',
    ],
  },
  {
    id: 'bm-16-nckh',
    code: 'BM16/QTQL.NC2.1.1',
    name: 'Mẫu Biên bản giải trình chỉnh sửa sau nghiệm thu',
    description: 'Bản giải trình chi tiết về việc chỉnh sửa báo cáo kết quả đề tài theo ý kiến kết luận của Hội đồng nghiệm thu.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'WORD',
    size: '44 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 14/2014/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM16_QTQL.NC2.1.1_Bien_ban_giai_trinh_sau_nghiem_thu.docx',
    previewSummary: [
      '1. Tổng hợp ý kiến chỉnh sửa của Hội đồng nghiệm thu',
      '2. Nội dung tiếp thu giải trình và sửa đổi chi tiết',
      '3. Xác nhận hoàn thiện của Thư ký Hội đồng nghiệm thu',
      '4. Phê duyệt của Phòng Quản lý NCKH',
    ],
  },
  {
    id: 'bm-17-nckh',
    code: 'BM17/QTQL.NC2.1.1',
    name: 'Mẫu Quyết định công nhận kết quả nghiệm thu',
    description: 'Quyết định hành chính chính thức của Giám đốc Viện/Bệnh viện công nhận kết quả nghiệm thu và thanh lý hợp đồng đề tài.',
    category: 'ACCEPTANCE',
    categoryLabel: 'Hội đồng Nghiệm thu',
    format: 'WORD',
    size: '38 KB',
    updatedAt: '01/01/2026',
    legalRef: 'Thông tư số 11/2014/TT-BKHCN',
    templateVersion: 'v2.1',
    downloadFileName: 'BM17_QTQL.NC2.1.1_Quyet_dinh_cong_nhan_ket_qua_nghiem_thu.docx',
    previewSummary: [
      '1. Căn cứ Biên bản nghiệm thu đạt yêu cầu của Hội đồng',
      '2. Công nhận kết quả xếp loại khoa học chính thức',
      '3. Phê duyệt quyết toán và thu hồi/hoàn trả kinh phí thừa thiếu',
      '4. Trách nhiệm lưu trữ và chuyển giao ứng dụng lâm sàng',
    ],
  },
];
