export const ROLES = {
  RESEARCHER: 'RESEARCHER',
  RESEARCH_OFFICE: 'RESEARCH_OFFICE',
  COUNCIL_MEMBER: 'COUNCIL_MEMBER',
  COUNCIL_SECRETARY: 'COUNCIL_SECRETARY',
  ETHICS_OFFICE: 'ETHICS_OFFICE',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  DIRECTOR: 'DIRECTOR',
  ADMIN: 'ADMIN',
} as const;

export const PROJECT_STATUS = {
  DRAFT: 'DRAFT',
  PROPOSAL_APPROVED: 'PROPOSAL_APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  ACCEPTED: 'ACCEPTED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
  REJECTED: 'REJECTED',
  TERMINATED: 'TERMINATED',
  SUSPENDED: 'SUSPENDED',
} as const;

export const PROPOSAL_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_ADMIN_REVIEW: 'UNDER_ADMIN_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  RESUBMITTED: 'RESUBMITTED',
  VALID: 'VALID',
  REJECTED: 'REJECTED',
} as const;

export const COUNCIL_STATUS = {
  DRAFT: 'DRAFT',
  ESTABLISHED: 'ESTABLISHED',
  EVALUATING: 'EVALUATING',
  MINUTES_DRAFTED: 'MINUTES_DRAFTED',
  CONCLUDED: 'CONCLUDED',
  DISSOLVED: 'DISSOLVED',
} as const;

export const ETHICS_STATUS = {
  NOT_REQUIRED: 'NOT_REQUIRED',
  DOSSIER_SUBMITTED: 'DOSSIER_SUBMITTED',
  UNDER_ETHICS_REVIEW: 'UNDER_ETHICS_REVIEW',
  ETHICS_REVISION_REQUIRED: 'ETHICS_REVISION_REQUIRED',
  ETHICS_APPROVED: 'ETHICS_APPROVED',
  ETHICS_EXPIRED: 'ETHICS_EXPIRED',
  ETHICS_REJECTED: 'ETHICS_REJECTED',
} as const;

export const PROGRESS_REPORT_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  REJECTED: 'REJECTED',
} as const;

export const CHANGE_REQUEST_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const ACCEPTANCE_DOSSIER_STATUS = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  SUBMITTED: 'SUBMITTED',
  PRE_CHECKED: 'PRE_CHECKED',
  COUNCIL_ASSIGNED: 'COUNCIL_ASSIGNED',
  EVALUATED: 'EVALUATED',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;

export const FINANCIAL_VOUCHER_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
