export const ROLES = {
  RESEARCHER: 'RESEARCHER',
  RESEARCH_OFFICE: 'RESEARCH_OFFICE',
  COUNCIL_MEMBER: 'COUNCIL_MEMBER',
  ETHICS_OFFICE: 'ETHICS_OFFICE',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  DIRECTOR: 'DIRECTOR',
  ADMIN: 'ADMIN',
} as const;

export const CouncilStatus = {
  DRAFT: 'DRAFT',
  ESTABLISHED: 'ESTABLISHED',
  EVALUATING: 'EVALUATING',
  MINUTES_DRAFTED: 'MINUTES_DRAFTED',
  CONCLUDED: 'CONCLUDED',
  DISSOLVED: 'DISSOLVED',
} as const;

export const ProgressReportStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  REJECTED: 'REJECTED',
} as const;

export const ChangeRequestStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  RESUBMITTED: 'RESUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const AcceptanceDossierStatus = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_ADMIN_REVIEW: 'UNDER_ADMIN_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  RESUBMITTED: 'RESUBMITTED',
  ELIGIBLE_FOR_ACCEPTANCE: 'ELIGIBLE_FOR_ACCEPTANCE',
  FORWARDED_TO_COUNCIL: 'FORWARDED_TO_COUNCIL',
} as const;

export const FinanceStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  AWAITING_FINALIZATION: 'AWAITING_FINALIZATION',
  FINALIZED: 'FINALIZED',
  CLOSED: 'CLOSED',
} as const;