// Canonical runtime constants for state machine values
// Use these to avoid ad-hoc string literals across the codebase
export const ProposalStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_ADMIN_REVIEW: 'UNDER_ADMIN_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  RESUBMITTED: 'RESUBMITTED',
  VALID: 'VALID',
  PROPOSAL_REVISION_REQUIRED: 'PROPOSAL_REVISION_REQUIRED',
  PROPOSAL_RESUBMITTED: 'PROPOSAL_RESUBMITTED',
  UNDER_PROPOSAL_REVISION_REVIEW: 'UNDER_PROPOSAL_REVISION_REVIEW',
  PROPOSAL_APPROVED: 'PROPOSAL_APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const ProjectStatus = {
  DRAFT: 'DRAFT',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  WAITING_ASSIGNMENT: 'WAITING_ASSIGNMENT',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_ACCEPTANCE: 'WAITING_ACCEPTANCE',
  ACCEPTED: 'ACCEPTED',
  RECOGNIZED: 'RECOGNIZED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED',
  REJECTED: 'REJECTED',
} as const;

export const EthicsStatus = {
  NOT_REQUIRED: 'NOT_REQUIRED',
  SCREENING_IN_PROGRESS: 'SCREENING_IN_PROGRESS',
  DOSSIER_SUBMITTED: 'DOSSIER_SUBMITTED',
  UNDER_ETHICS_REVIEW: 'UNDER_ETHICS_REVIEW',
  ETHICS_REVISION_REQUIRED: 'ETHICS_REVISION_REQUIRED',
  CONDITIONALLY_APPROVED: 'CONDITIONALLY_APPROVED',
  ETHICS_APPROVED: 'ETHICS_APPROVED',
  ETHICS_REJECTED: 'ETHICS_REJECTED',
  EXPIRED: 'EXPIRED',
  SUSPENDED: 'SUSPENDED',
  WITHDRAWN: 'WITHDRAWN',
  TERMINATED: 'TERMINATED',
} as const;

export type ProposalStatusKey = keyof typeof ProposalStatus;
export type ProjectStatusKey = keyof typeof ProjectStatus;
export type EthicsStatusKey = keyof typeof EthicsStatus;

export default {
  ProposalStatus,
  ProjectStatus,
  EthicsStatus,
};
